import {SETTINGS,pauseWorld,clearPendingInput,getJumpReadiness,selectFoodTarget} from './core.js';
import {createStory,stepStory,retryStory,returnFromStoryInquiry,openStoryInquiry,storyMission,storyRecord,serializeStory,restoreStory,STORY_STAGES,STORY_RULE_NOTE,STORY_SOURCE_NOTE} from './story.js';
import {createRenderer} from './render.js';
import {createInput,GAME_KEYS} from './input.js';
import {loadAssets} from './assets.js';
import {createAudio} from './audio.js';
import {predatorSignal} from './predator-signals.js';
import {mountStoryInquiry} from './story-inquiry.js';
import {titleLayout} from './title-layout.js';
const $=id=>document.getElementById(id),canvas=$('world'),dialog=$('dialog');
const renderer=createRenderer(canvas),input=createInput({tapEating:true}),sound=createAudio({muted:false,volume:.35});
const KEY='eat-escape-story-v05';
let record={version:1,knowledge:{},inquiryStates:{},stages:[],saved:null,completed:false},storageOK=true;
try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(v?.version===1)record={...record,...v};}catch{storageOK=false;}
record.stages=Array.isArray(record.stages)?record.stages.slice(-4):[];
let settings={sound:true,showTouch:true,longWarning:false,slowPredators:false},assets=null,active=false,world=null,lab=null,dialogKind='',pausedBeforeDialog=false,last=performance.now(),accumulator=0,lastEvent=0,lastSize=null,resizeQueued=false,scene=null,lastSavedTime=0,activeLabKind=null;
const captured=new Map();
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const p=t=>el('p',t);
const button=(t,fn,cls='')=>{const n=el('button',t,cls);n.type='button';n.addEventListener('click',fn);return n;};
function save(){try{localStorage.setItem(KEY,JSON.stringify(record));return true;}catch{storageOK=false;return false;}}
function saveWorld(){if(lab&&activeLabKind)record.inquiryStates[activeLabKind]=lab.getState();if(world?.story&&['playing','failed'].includes(world.status)){record.saved=serializeStory(world);record.knowledge={...world.knowledge};if(lab)record.inquiryStates[activeLabKind??world.storyConfig.inquiry]=lab.getState();}save();}
function announce(t){$('announcement').textContent=t;}
function drawStick(){const s=input.stick;$('stick').style.transform=`translate(${s.x*30}px,${s.y*30}px)`;}
function clear(){input.clear();if(world)clearPendingInput(world);for(const[id,n]of captured)try{if(n.hasPointerCapture(id))n.releasePointerCapture(id);}catch{}captured.clear();drawStick();}
function pause(reason='잠깐 쉬어 가요'){if(!active)return;pauseWorld(world,true);input.setEnabled(false);clear();sound.stop();$('pause-reason').textContent=reason;$('pause-overlay').hidden=dialog.open||Boolean(scene);accumulator=0;saveWorld();}
function resume(){if(!active||dialog.open||scene||world.status!=='playing')return;pauseWorld(world,false);input.setEnabled(true);$('pause-overlay').hidden=true;last=performance.now();accumulator=0;canvas.focus({preventScroll:true});sound.unlock();}
function rememberLab(){if(lab){record.inquiryStates[activeLabKind??world.storyConfig.inquiry]=lab.getState();if(world)world.inquiryStates[activeLabKind??world.storyConfig.inquiry]=lab.getState();lab.destroy();lab=null;activeLabKind=null;save();}}
function openDialog(title,kind='general',wide=false){rememberLab();if(!dialog.open)pausedBeforeDialog=world?.paused??true;dialogKind=kind;if(active)pause();$('pause-overlay').hidden=true;$('dialog-title').textContent=title;$('dialog-content').replaceChildren();dialog.classList.toggle('wide',wide);$('dialog-close').hidden=['result','intro'].includes(kind);if(!dialog.open)dialog.showModal();return $('dialog-content');}
function closeDialog({resumeGame=true,forceResume=false}={}){rememberLab();if(dialog.open)dialog.close();dialogKind='';if(active&&resumeGame){if(forceResume||!pausedBeforeDialog)resume();else pause();}}
function row(box,...nodes){const r=el('div',undefined,'button-row');r.append(...nodes);box.append(r);}
function refreshHome(){$('completion-summary').textContent=record.completed?'네 장면을 모두 건넜어요 · 발견 기록은 이 기기에 남아요':'네 장면으로 이어지는 같은 연못의 이야기';$('checkpoint-resume').hidden=!record.saved;$('checkpoint-resume').textContent=record.saved?`${record.saved.stage}장부터 이어가기`:'이어서 하기';$('start').disabled=!assets;}
function home(){if(active){saveWorld();pause();}scene=null;$('story-caption').hidden=true;closeDialog({resumeGame:false});active=false;$('game').hidden=true;$('entry').hidden=false;document.body.classList.add('title-screen');refreshHome();}
function installWorld(w,{camera=false}={}){closeDialog({resumeGame:false});world=w;active=true;lastEvent=w.events.length;lastSize=null;scene=null;lastSavedTime=world.time;$('entry').hidden=true;$('story-caption').hidden=true;document.body.classList.remove('title-screen');$('game').hidden=false;if(!camera)renderer.resetCamera();renderer.resize();renderer.render(world,0);resume();resize();hud();saveWorld();}
function start(stage=1,{previous=null}={}){if(stage===1){record.stages=[];record.completed=false;}installWorld(createStory(stage,{previous,knowledge:record.knowledge,settings}),{camera:stage===2});}
function resumeSaved(){const w=restoreStory(record.saved,{settings});if(!w){record.saved=null;save();refreshHome();intro();return;}installWorld(w);if(w.phase==='at-inquiry')openLab();}
function intro(){const b=openDialog('새 풀밭으로 가 볼까?','intro');b.append(el('span','1/4 · 나는 메뚜기','role-pill'),p('새 풀잎을 찾아 나온 메뚜기. 개구리를 피해 저 너머 빽빽한 새 풀밭까지 가요. 이 만남은 곧 다른 동물의 이야기로 이어져요.'),el('p','목적지: 새 풀밭  ·  조심할 동물: 개구리','intro-target'));
 const controls=el('div',undefined,'intro-controls');for(const [name,detail]of [['이동','방향키 · WASD / 왼쪽 조이스틱'],['먹기','J · Z / 오른쪽 먹기 한 번'],['도약','Space · K · X / 오른쪽 도약']]){const c=el('div');c.append(el('strong',name),el('span',detail));controls.append(c);}b.append(controls);const facts=el('div',undefined,'intro-facts');['시간제한 없음','하트 3개','먹으면 도약 힘 +1'].forEach(t=>facts.append(el('span',t)));b.append(facts,p('먹을 풀과 숨는 풀을 살펴보고 길을 골라요. 도약 힘이 없어도 걸어서 갈 수 있어요. 안전한 풀에서는 잠깐 멈추고 직접 살펴볼 수 있어요.'),el('p',STORY_RULE_NOTE,'note'));row(b,button('메뚜기로 출발',()=>start(),'primary'),button('시작 화면',home));}
function help(){const b=openDialog('이동 · 먹기 · 도약');b.append(p('이동: 방향키·WASD 또는 왼쪽 조이스틱'),p('먹기: J·Z 또는 먹기를 한 번 눌러요. 메뚜기는 낮은 먹이풀 가까이, 개구리는 곤충에 노란 표식이 보일 때 먹을 수 있어요. 길게 눌러도 계속 먹지는 않아요.'),p('도약: Space·K·X 또는 도약. 힘 한 칸을 써서 크게 뛰어요. 먹으면 힘 한 칸과 하트를 채워요. 힘은 세 칸까지예요. 힘이 없어도 걸어서 가거나 옆으로 피해요.'),p('천적이 고개를 들며 공격 준비를 하면 공격 방향 옆으로 움직이거나 뛰어요. 이미 공격이 시작된 뒤에는 풀숲도 공격 경로를 막지 못해요. 뱀의 긴 몸통은 돌아가거나 뛰어넘어요.'),p('하트가 없어지면 마지막 쉼터에서 다시 도전해요. 살펴본 내용과 지나온 길은 남아요. 탐구 중에는 동물과 게임 시간이 멈춰요.'),el('p',STORY_RULE_NOTE,'note'));
 for(const[key,label]of [['showTouch','화면 조작 버튼 표시'],['sound','효과음 켜기'],['longWarning','공격 준비를 더 길게 보여 주기'],['slowPredators','천적을 천천히 움직이기']]){const r=el('label',undefined,'proof-setting'),c=el('input');c.type='checkbox';c.checked=settings[key];c.onchange=()=>{settings[key]=c.checked;if(world)world.settings[key]=c.checked;document.body.classList.toggle('touch-ui',settings.showTouch);sound.setMuted(!settings.sound);resize();};r.append(c,document.createTextNode(label));b.append(r);}row(b,button(active?'계속하기':'닫기',()=>closeDialog(),'primary'));}
function showRecords(b){for(const r of record.stages){const foods=[...new Set(r.foods??[])].join(' / ')||'먹지 않고 건넜어요';b.append(el('h3',`${r.stage}장 · ${r.title}`),p(`실제로 먹은 관계: ${foods}`),p(`점수 ${r.points} · 붙잡힘 ${r.captures}번 · 살펴보기 ${r.inquiry?(r.reviewedLater?'도착 뒤 완료':'완료'):'아직'} · 게임 시간 ${r.seconds}초`));if(r.stage===2)b.append(p(`고른 먹이 조건: ${r.fieldCondition==='absent'?'메뚜기 없음 · 애벌레는 그대로':'메뚜기 있음 · 애벌레도 있음'}`));if(r.observed?.length)b.append(p('눈앞에서 본 관계: '+[...new Set(r.observed)].join(' / ')));}}
function reviewInquiry(kind){const titles={plant:'풀과 햇빛 다시 살펴보기',food:'먹이 두 조건 다시 살펴보기',habitat:'달라진 풀밭 다시 살펴보기',decomposer:'낙엽의 긴 변화 다시 살펴보기'};const b=openDialog(titles[kind],'lab-review',true);activeLabKind=kind;lab=mountStoryInquiry(b,{kind,assets,initialState:record.inquiryStates[kind],onClose:state=>{record.inquiryStates[kind]=state;notes();},onComplete:evidence=>{record.knowledge[kind]=evidence;if(world)world.knowledge[kind]=evidence;const r=record.stages.find(s=>STORY_STAGES[s.stage-1]?.inquiry===kind);if(r&&!r.inquiry){r.inquiry=true;r.reviewedLater=true;}save();notes();}});}
function notes(){const b=openDialog('먹이 관계와 발견 기록');for(const[k,v]of Object.entries(record.knowledge)){b.append(el('h3',({plant:'풀과 햇빛',food:'개구리의 먹이',habitat:'달라진 풀밭',decomposer:'낙엽의 긴 변화'})[k]??'발견'),p(v.summary??'직접 바꿔 살펴본 결과가 저장되었어요.'));}showRecords(b);if(record.stages.some(r=>!r.inquiry)){b.append(el('h3','아직 남은 발견'));for(const r of record.stages.filter(r=>!r.inquiry)){const kind=STORY_STAGES[r.stage-1].inquiry;b.append(button(`${r.stage}장 살펴보기 이어서`,()=>reviewInquiry(kind)));}}b.append(el('h3','이 이야기의 바탕이 된 관계'),el('div','풀 → 메뚜기 → 개구리 → 뱀\n풀 → 애벌레 → 개구리\n애벌레 → 오리 ← 개구리','foodweb-card'),p('화살표는 먹이에서 먹는 생물 쪽으로 향해요. 공격 방향 표시와는 뜻이 달라요. 기본 관계와 내가 직접 본 기록은 구분해요.'),el('p',STORY_SOURCE_NOTE,'note'),el('p','식물은 햇빛을 이용해 스스로 양분을 만들어요. 모형의 시간 손잡이는 여러 날의 과정을 빠르게 살펴보기 위한 도구예요. 실제 생태계의 개체 수를 예측하지 않아요.','note'));if(active&&world.status==='playing')row(b,button('이 장면 다시 살펴보기',()=>{closeDialog({resumeGame:false});openStoryInquiry(world);openLab();},'primary'));if(!storageOK)b.append(p('이 브라우저는 저장을 허용하지 않아 이번 창에서만 기록을 유지해요.'));row(b,button('닫기',()=>closeDialog(),'primary'));}
function info(){const b=openDialog('같은 연못, 이어지는 네 장면');for(const s of STORY_STAGES)b.append(el('h3',`${s.id}. ${s.title}`),p(s.intro),p(`도착할 곳: ${s.goal} · 조심할 동물: ${s.risk}`));b.append(p('먹이 수를 채워 문을 여는 게임이 아니에요. 먹을 곳, 숨을 곳, 도약할 때를 고르며 길을 건너요. 점수는 길 발견과 직접 살펴보기에 따라 쌓여요.'));row(b,button('닫기',()=>closeDialog(),'primary'));}
function openLab(){const kind=world.storyConfig.inquiry;const b=openDialog(({plant:'풀은 어떻게 양분을 만들까?',food:'개구리는 무엇을 먹을까?',habitat:'같은 풀밭이 어떻게 달라졌을까?',decomposer:'낙엽은 오래 지나면 어떻게 될까?'})[kind],'lab',true);activeLabKind=kind;lab=mountStoryInquiry(b,{kind,assets,initialState:record.inquiryStates[kind],onClose:state=>{record.inquiryStates[kind]=state;returnFromStoryInquiry(world);closeDialog({forceResume:true});saveWorld();},onComplete:evidence=>{record.knowledge[kind]=evidence;record.inquiryStates[kind]=lab?.getState();returnFromStoryInquiry(world,evidence);closeDialog({forceResume:true});saveWorld();announce('발견을 저장했어요. 같은 자리에서 이어가요');}});}
function closeLab(){if(world?.phase==='at-inquiry'){rememberLab();returnFromStoryInquiry(world);}closeDialog({forceResume:true});saveWorld();}
function beginScene(){pause();scene={elapsed:0,next:world.stage+1,old:world,nextWorld:createStory(world.stage+1,{previous:world,knowledge:record.knowledge,settings})};record.saved=serializeStory(scene.nextWorld);save();$('pause-overlay').hidden=true;$('story-caption').hidden=false;$('story-caption').textContent=world.stage===1?'메뚜기가 풀숲으로 숨었어요. 먹이를 놓친 개구리는 어디로 갈까요?':world.stage===2?'며칠 뒤, 같은 연못… 산책로 옆 풀이 베어졌어요.':'해가 기울어요. 남은 풀숲을 따라 마지막 은신처로!';if(world.stage===1)world.cameraFocus={x:world.predator.x,y:world.predator.y};}
function result(){if(world.status==='success'){if(!world.recorded){const r=storyRecord(world);record.stages=record.stages.filter(x=>x.stage!==r.stage);record.stages.push(r);record.knowledge={...world.knowledge};world.recorded=true;record.saved=null;save();}if(world.stage<4){beginScene();return;}record.completed=true;save();const b=openDialog('같은 연못의 네 장면을 건넜어요!','result');b.append(el('p',`모은 점수 ${record.stages.reduce((n,r)=>n+r.points,0)} · 네 곳에 무사히 도착`,'intro-target'),p('풀을 먹던 메뚜기가 숨자, 바로 그 개구리의 길이 이어졌어요. 개구리는 곤충을 먹지만 뱀과 오리에게는 먹이가 될 수 있었어요.'),p('풀이 베어진 뒤에는 남아 있는 먹이터와 풀숲을 다시 찾아야 했어요. 어떤 길을 골랐는지 내 기록을 살펴봐요.'));showRecords(b);const missing=record.stages.filter(r=>!r.inquiry).length;if(missing){b.append(p(`아직 살펴보지 않은 발견이 ${missing}개 남았어요. 지금 안전하게 이어서 해 볼까요?`));row(b,button('남은 발견 이어서 보기',notes,'primary'));}b.append(el('p','이 기록은 내가 게임에서 실제로 한 행동이에요. 게임의 짧은 시간으로 실제 자연의 생물 수 변화를 예측할 수는 없어요.','note'));row(b,button('다른 길로 처음부터',()=>start(),'primary'),button('발견 기록',notes),button('시작 화면',home));return;}
 const b=openDialog('마지막 쉼터에서 다시!','result');b.append(p('살펴본 내용과 지나온 길은 남아 있어요. 천적이 공격을 준비할 때 옆으로 움직여도 피할 수 있어요.'));row(b,button('쉼터부터 다시',()=>{retryStory(world);closeDialog({forceResume:true});saveWorld();},'primary'),button('도움 설정',help),button('시작 화면',home));}
async function prepare(){try{assets=await loadAssets();renderer.setAssets(assets);$('asset-status').hidden=true;$('retry-assets').hidden=true;}catch(e){$('asset-status').hidden=false;$('asset-status').textContent='그림을 불러오지 못했어요. 다시 시도해 주세요';$('retry-assets').hidden=false;}refreshHome();}
$('start').onclick=()=>{sound.unlock();intro();};$('retry-assets').onclick=prepare;$('entry-stages').onclick=info;$('stages').onclick=info;for(const id of ['entry-teacher','teacher','records'])$(id).onclick=notes;for(const id of ['entry-settings','help','compact-help'])$(id).onclick=help;$('checkpoint-resume').onclick=resumeSaved;$('pause-home').onclick=home;$('resume').onclick=resume;$('pause').onclick=()=>world.paused?resume():pause();$('dialog-close').onclick=()=>dialogKind==='lab'?closeLab():dialogKind==='lab-review'?notes():closeDialog();dialog.oncancel=e=>{e.preventDefault();if(['result','intro'].includes(dialogKind))return;dialogKind==='lab'?closeLab():dialogKind==='lab-review'?notes():closeDialog();};
window.addEventListener('keydown',e=>{if(!active||dialog.open)return;if(e.code==='Escape'){if(!e.repeat)world.paused?resume():pause();e.preventDefault();return;}if(!GAME_KEYS.has(e.code)||world.paused||world.status!=='playing')return;if(document.activeElement?.matches('input,textarea,select'))return;e.preventDefault();input.keyDown(e.code,e.repeat);});window.addEventListener('keyup',e=>input.keyUp(e.code));
function capture(n,id){try{n.setPointerCapture(id);captured.set(id,n);}catch{input.endPointer(id,true);}}
function release(e){input.endPointer(e.pointerId,e.type!=='pointerup');const n=captured.get(e.pointerId);captured.delete(e.pointerId);try{if(n?.hasPointerCapture(e.pointerId))n.releasePointerCapture(e.pointerId);}catch{}drawStick();}
function padPoint(e){const b=$('pad').getBoundingClientRect();return[e.pointerId,e.clientX-b.left-b.width/2,e.clientY-b.top-b.height/2,b.width*.34];}
$('pad').onpointerdown=e=>{e.preventDefault();if(input.startPad(...padPoint(e))){capture($('pad'),e.pointerId);drawStick();}};$('pad').onpointermove=e=>{if(input.updatePad(...padPoint(e))){e.preventDefault();drawStick();}};
for(const[id,action]of [['eat','eat'],['jump','jump']]){$(id).onpointerdown=e=>{e.preventDefault();if(input.startAction(e.pointerId,action))capture($(id),e.pointerId);};$(id).onclick=e=>{if(e.detail===0)input.queue(action);};}
for(const n of [$('pad'),$('eat'),$('jump')]){for(const t of ['pointerup','pointercancel','lostpointercapture'])n.addEventListener(t,release);n.oncontextmenu=e=>e.preventDefault();}
canvas.onpointerdown=()=>canvas.focus({preventScroll:true});
function resize(){if(resizeQueued)return;resizeQueued=true;requestAnimationFrame(()=>{resizeQueued=false;document.documentElement.style.setProperty('--app-height',`${window.visualViewport?.height??innerHeight}px`);document.documentElement.style.setProperty('--app-width',`${window.visualViewport?.width??innerWidth}px`);const titleBox=$('app').getBoundingClientRect(),title=titleLayout(titleBox.width||(window.visualViewport?.width??window.innerWidth),titleBox.height||(window.visualViewport?.height??window.innerHeight));const titleSrc=globalThis.__ECOLOGY_EMBEDDED_ASSETS__?.[title.asset]??new URL(`../assets/${title.path}`,import.meta.url).href;if($('title-image').src!==titleSrc){$('title-image').src=titleSrc;$('title-backdrop').src=titleSrc;}for(const [key,value]of Object.entries(title.art))$('entry-art').style.setProperty(`--title-${key}`,`${value}px`);for(const[key,value]of Object.entries(title.button))$('entry').style.setProperty(`--start-${key}`,`${value}px`);$('entry').classList.toggle('blended-title',title.blended);$('entry').dataset.blend=title.blendAxis;if(!active)return;const b=canvas.getBoundingClientRect();if(lastSize&&(Math.abs(b.width-lastSize.width)>1||Math.abs(b.height-lastSize.height)>1))pause('화면 크기가 바뀌었어요');lastSize={width:b.width,height:b.height};renderer.resize();renderer.render(world,0);});}
window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);if('ResizeObserver'in window)new ResizeObserver(resize).observe($('playfield'));window.addEventListener('blur',()=>{if(active)pause('다른 창으로 이동했어요');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause('화면을 잠시 떠났어요');});window.addEventListener('pagehide',()=>{saveWorld();if(active)pause();});
function hud(){const p=world.player,r=getJumpReadiness(world),target=selectFoodTarget(world),mission=storyMission(world);$('stage-label').textContent=`${world.stage}/4 · 나는 ${world.role==='grasshopper'?'메뚜기':'개구리'}`;$('food').textContent=`도약 힘 ${'●'.repeat(world.jumpEnergy)}${'○'.repeat(3-world.jumpEnergy)}`;$('timer').textContent=`${world.points}점`;$('timer').setAttribute('title',`시간제한 없음 · 플레이 ${Math.floor(world.time)}초`);$('escape').textContent='♥'.repeat(world.hearts)+'♡'.repeat(3-world.hearts);$('mission').textContent=mission.title;$('mission-progress').textContent=mission.progress;const signal=predatorSignal(world);$('state').textContent=signal.label;$('state').dataset.threat=signal.kind;$('jump').setAttribute('aria-disabled',String(!r.ready));$('jump-label').textContent=r.label;
 const closeFood=world.role==='frog'&&!target&&world.prey.some(q=>q.alive&&!q.captured&&Math.abs(q.x-p.x)<=60&&Math.hypot(q.x-p.x,(q.y-p.y)*.62)<=185),airborne=p.state==='jumping',busy=p.state==='eating'||p.eatCooldown>0,canEat=!world.paused&&!airborne&&!busy&&Boolean(target);$('eat-label').textContent=world.paused?'잠깐 멈춤':airborne?'착지 후 먹기':busy?'먹는 중':target?'한 번 누르기':world.role==='grasshopper'?'낮은 풀 가까이':closeFood?'조금 떨어지기':'곤충 가까이';$('eat').setAttribute('aria-disabled',String(!canEat));$('eat').dataset.ready=String(canEat);$('status').textContent=signal.active?signal.detail:p.feedback?.text??mission.next;$('condition-label').textContent=`목적지: ${world.storyConfig.goal} · 조심: ${world.storyConfig.risk}`;$('pause').textContent=world.paused?'계속':'멈춤';}
function events(){for(const e of world.events.slice(lastEvent)){if(e.type==='ate'||e.type==='npc-ate')sound.play('eat');if(e.type==='jump')sound.play('jump');if(e.type==='predator-warning')sound.play('warning');if(e.type==='escape-used')sound.play('escape');if(e.type==='shelter-checkpoint'||e.type==='story-landmark')saveWorld();}lastEvent=world.events.length;}
function frame(now){let dt=Math.min(.1,Math.max(0,(now-last)/1000));if(now-last>350&&active&&!world.paused)pause('실행이 잠시 중단됐어요');last=now;if(active){renderer.render(world,dt);if(scene){scene.elapsed+=dt;if(world.stage===1)world.storyHideAmount=Math.min(1,scene.elapsed/1.2);if(scene.elapsed>3.8){const nextWorld=scene.nextWorld;installWorld(nextWorld,{camera:nextWorld.stage===2});}}else{if(!world.paused)accumulator+=dt;else accumulator=0;while(accumulator>=SETTINGS.fixedStep){stepStory(world,input.consume(world.player),SETTINGS.fixedStep);accumulator-=SETTINGS.fixedStep;if(world.paused||world.status!=='playing')break;}events();hud();if(world.time-lastSavedTime>=5){lastSavedTime=world.time;saveWorld();}if(world.phase==='at-inquiry'&&!dialog.open)openLab();if(world.status!=='playing'&&!dialog.open)result();}}requestAnimationFrame(frame);}
document.body.classList.add('touch-ui','title-screen');refreshHome();prepare();resize();requestAnimationFrame(frame);
