import {SETTINGS,pauseWorld,clearPendingInput,getJumpReadiness,selectFoodTarget} from './core.js';
import {createJourney,stepJourney,retryJourney,applyDiscovery} from './journey.js';
import {createRenderer} from './render.js';
import {createInput,GAME_KEYS} from './input.js';
import {loadAssets} from './assets.js';
import {createAudio} from './audio.js';
import {predatorSignal} from './predator-signals.js';
import {makeJourneyRecord,restoreJourneyRecords,formatJourneyRecord,formatJourneyComparison,JOURNEY_RECORD_CAUTION} from './journey-record.js';
import {mountInquiry} from './inquiry.js';

const $=id=>document.getElementById(id),canvas=$('world'),dialog=$('dialog');
const renderer=createRenderer(canvas),input=createInput(),sound=createAudio({muted:false,volume:.35});
const KEY='eat-escape-fun-proof-v01';
let record={knowledge:null,labState:null,hopperComplete:false,complete:false},storageOK=true;
try{record={...record,...JSON.parse(localStorage.getItem(KEY)||'{}')};}catch{storageOK=false;}
record.journeys=restoreJourneyRecords(record.journeys);
let settings={sound:true,showTouch:true,longWarning:false,slowPredators:false},assets=null,active=false,world=null,lab=null,dialogKind='',pausedBeforeDialog=false,last=performance.now(),accumulator=0,lastEvent=0,lastSize=null,resizeQueued=false;
const captured=new Map();
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const p=t=>el('p',t);
const button=(t,fn,cls='')=>{const n=el('button',t,cls);n.type='button';n.addEventListener('click',fn);return n;};
function save(){try{localStorage.setItem(KEY,JSON.stringify(record));return true;}catch{storageOK=false;return false;}}
function rememberJourney(){if(world.savedJourneyRecord)return world.savedJourneyRecord;const snapshot=makeJourneyRecord(world);if(!snapshot)return null;record.journeys=restoreJourneyRecords([...(record.journeys??[]),snapshot]);world.savedJourneyRecord=snapshot;save();return snapshot;}
function showJourneyRecords(box){const recent=(record.journeys??[]).slice(-2);if(!recent.length)return;box.append(el('h3',recent.length>1?'최근 두 번의 귀환 기록':'최근 귀환 기록'),el('div',recent.length>1?formatJourneyComparison(...recent):formatJourneyRecord(recent[0])+'\n'+JOURNEY_RECORD_CAUTION,'foodweb-card'));}
function announce(t){$('announcement').textContent=t;}
function drawStick(){const s=input.stick;$('stick').style.transform=`translate(${s.x*30}px,${s.y*30}px)`;}
function clear(){input.clear();if(world)clearPendingInput(world);for(const[id,n]of captured)try{if(n.hasPointerCapture(id))n.releasePointerCapture(id);}catch{}captured.clear();drawStick();}
function pause(reason='잠깐 쉬어 가요'){if(!active)return;pauseWorld(world,true);input.setEnabled(false);clear();sound.stop();$('pause-reason').textContent=reason;$('pause-overlay').hidden=dialog.open;accumulator=0;}
function resume(){if(!active||dialog.open||world.status!=='playing')return;pauseWorld(world,false);input.setEnabled(true);$('pause-overlay').hidden=true;last=performance.now();accumulator=0;canvas.focus({preventScroll:true});sound.unlock();}
function openDialog(title,kind='general',wide=false){if(lab){record.labState=lab.getState();save();lab.destroy();lab=null;}if(!dialog.open)pausedBeforeDialog=world?.paused??true;dialogKind=kind;if(active)pause();$('pause-overlay').hidden=true;$('dialog-title').textContent=title;$('dialog-content').replaceChildren();dialog.classList.toggle('wide',wide);$('dialog-close').hidden=['transition','result','intro'].includes(kind);if(!dialog.open)dialog.showModal();return $('dialog-content');}
function closeDialog({resumeGame=true,forceResume=false}={}){if(lab){record.labState=lab.getState();save();lab.destroy();lab=null;}if(dialog.open)dialog.close();dialogKind='';if(active&&resumeGame){if(forceResume||!pausedBeforeDialog)resume();else pause();}}
function row(box,...nodes){const r=el('div',undefined,'button-row');r.append(...nodes);box.append(r);}
function refreshHome(){$('completion-summary').textContent=record.complete?'체험 완료 · 발견한 먹이 길은 이 기기에 남아요':record.knowledge?'발견 노트 저장됨 · 다시 잡혀도 발견은 남아요':'조작은 이동·먹기·도약 세 가지';$('checkpoint-resume').hidden=!record.hopperComplete;$('start').disabled=!assets;}
function home(){if(active)pause();closeDialog({resumeGame:false});active=false;$('game').hidden=true;$('entry').hidden=false;refreshHome();}
function start(role='grasshopper'){closeDialog({resumeGame:false});world=createJourney(role,{knowledge:record.knowledge,settings});active=true;lastEvent=0;lastSize=null;$('entry').hidden=true;$('game').hidden=false;renderer.resetCamera();renderer.resize();renderer.render(world,0);resume();resize();}
function intro(){const b=openDialog('먹던 나도 누군가의 먹이!','intro');b.append(el('span','재미·탐구 체험판 0.3','role-pill'),el('p','메뚜기부터 출발해요','intro-target'),p('풀을 한입 먹고, 개구리를 피해 관찰소로 가세요. 천적이 공격을 준비하면 옆으로 피하거나 도약!'));
 const facts=el('div',undefined,'intro-facts');['이동 · 먹기 · 도약','하트 3개','풀숲은 쉼터'].forEach(t=>facts.append(el('span',t)));b.append(facts,p('이후에는 개구리가 됩니다. 관찰소에서 먹이 조건을 바꾸어 직접 살펴보고, 같은 들판에 돌아와 발견을 써 보세요.'));row(b,button('메뚜기로 출발',()=>start(),'primary'),button('시작 화면',home));}
function help(){const b=openDialog('딱 세 가지 조작');b.append(p('방향키 / WASD 또는 왼쪽 조이스틱: 이동'),p('J / Z 또는 먹기: 풀에서는 누르고 있기, 개구리는 표식이 뜬 먹이를 한 번에 낚아채기'),p('K / X / SPACE 또는 도약: 표시된 방향으로 크게 뛰기. 공격 방향의 옆으로 움직여도 피할 수 있어요. 뱀 몸통이 길을 막으면 돌아가거나 도약해 넘어요.'),p('뱀이 다가오다 머리와 목을 들면 공격 준비예요. 준비 중에는 아직 잡히지 않지만, 표시된 길로 돌진하면 잡혀요. 몸통은 길을 막아요. 이미 공격 준비를 시작한 뒤에는 풀숲에 들어가도 돌진 경로를 피해야 해요.'),p('풀숲은 몸을 숨기는 쉼터예요. 하트를 모두 잃어도 지나온 쉼터부터 바로 다시 시작하며, 실험에서 발견한 내용은 사라지지 않아요.'),p('하트와 먹자마자 회복하는 효과는 게임 규칙이에요. 실제 생물의 회복 속도를 나타내지 않아요.'));
 for(const[key,label]of [['showTouch','화면 조작 버튼 표시'],['sound','효과음 켜기'],['longWarning','공격 예고를 길게 (도움)'],['slowPredators','천적을 천천히 (도움)']]){const r=el('label',undefined,'proof-setting'),c=el('input');c.type='checkbox';c.checked=settings[key];c.onchange=()=>{settings[key]=c.checked;if(world)world.settings[key]=c.checked;document.body.classList.toggle('touch-ui',settings.showTouch);sound.setMuted(!settings.sound);resize();};r.append(c,document.createTextNode(label));b.append(r);}row(b,button(active?'계속하기':'닫기',()=>closeDialog(),'primary'));}
function notes(){const b=openDialog('나의 먹이 길 발견');if(record.knowledge)b.append(el('p','메뚜기가 없어도 다른 먹이 길이 있어요','intro-target'),p('관찰소에서 같은 조건으로 비교했을 때, 개구리는 메뚜기가 없는 조건에서 애벌레를 먹었어요. 이제 들판의 먹이 식물 가까이를 찾아보세요.'));else b.append(p('개구리 구간의 반짝이는 관찰소에서 두 조건을 직접 비교하면 여기에 발견이 남아요.'));
 showJourneyRecords(b);b.append(el('div','먹이 식물 → 메뚜기 → 개구리 → 뱀\n먹이 식물 → 애벌레 → 개구리','foodweb-card'),p('화살표는 먹이에서 먹는 생물 쪽으로 향해요. 게임의 공격 방향 표시와는 뜻이 달라요.'),el('p','식물은 햇빛으로 스스로 양분을 만드는 생산자예요. 이 짧은 체험판은 다섯 종류의 관계를 확인합니다. 더 넓은 먹이 그물과 상위 소비자는 다음 제작 범위예요.','note'));
 if(active&&world.role==='frog'&&world.phase==='find-lab'&&world.labDismissed)b.append(button('현장 관찰소 다시 열기',()=>{world.phase='at-lab';openLab();},'primary'));if(!storageOK)b.append(p('이 브라우저는 저장을 허용하지 않아 이번 창에서만 기록을 유지합니다.'));row(b,button('닫기',()=>closeDialog(),'primary'));}
function info(){const b=openDialog('이번에 해볼 것은 세 장면');b.append(p('1. 메뚜기: 식물을 먹고, 개구리의 혀를 피해 살아서 건너기'),p('2. 관찰소: 먹이 유무를 직접 바꾸고 같은 조건의 먹이 선택 비교하기'),p('3. 개구리: 빠른 먹이와 다른 먹이 길 중 선택하고, 뱀의 위치를 보며 관찰소로 돌아오기'),el('p','짧은 작동 체험판입니다. 전체 생물 구성·여섯 장은 아직 만들지 않았습니다. 실제 자연의 개체 수 변화를 예측하는 모형은 아닙니다.','note'));row(b,button(active?'현재 판으로':'시작 화면',()=>closeDialog(),'primary'));}
function openLab(){const b=openDialog('먹이 길을 바꾸어 볼까?','lab',true);lab=mountInquiry(b,{assets,initialState:record.labState,onClose:state=>{record.labState=state;save();if(world.phase==='at-lab'){world.phase='find-lab';world.labDismissed=true;}closeDialog({forceResume:true});},onComplete:evidence=>{record.knowledge=evidence;record.labState=lab?.getState()??record.labState;save();applyDiscovery(world,evidence);closeDialog({forceResume:true});announce('발견을 저장했어요. 같은 들판에서 먹이 길을 고르고, 관찰소로 돌아와요');}});}
function result(){if(world.status==='success'&&world.role==='grasshopper'){record.hopperComplete=true;save();const b=openDialog('무사히 건넜어요! 이번에는 개구리','transition');b.append(el('p','먹이였던 내가 사냥꾼이 된다면?','intro-target'),p('익숙한 먹이터가 비었어요. 다른 곳의 메뚜기를 쫓을까요, 다른 먹이를 찾아볼까요? 관찰소에서 먹이 길을 바꾸어 보고, 먹이를 찾아 나갔다가 뱀을 피해 관찰소로 돌아오세요.'));row(b,button('개구리로 출발',()=>start('frog'),'primary'));return;}
 if(world.status==='success'){record.complete=true;rememberJourney();save();const b=openDialog('먹이 길을 찾아 살아 돌아왔어요!','result');b.append(el('p','먹고, 피하고, 직접 알아냈어요','intro-target'),p(`이번 개구리 구간: 도약 ${world.events.filter(e=>e.type==='jump').length}회 · 천적 공격 ${world.events.filter(e=>e.type==='predator-attack').length}회 · 애벌레 먹이 길 ${world.applied?'관찰 후 활용':world.priorAlternative?'먼저 발견':'관찰로 발견'}`),p(world.applied?'관찰소에서 발견한 애벌레 먹이 길을 들판에서 사용했어요. 먹이 관계는 한 줄만 있는 것이 아니에요.':world.priorAlternative?'먼저 찾아낸 애벌레 먹이 길을 관찰소에서도 확인했어요. 먹이 관계는 여러 갈래로 이어집니다.':'이번에는 메뚜기 먹이 길로 돌아왔어요. 다음에는 관찰소에서 발견한 애벌레 길도 이용해 보세요.'),el('p','재미와 탐구 방식의 첫 체험입니다. 상위 소비자와 더 넓은 먹이 그물은 다음 검증 범위예요.','note'));showJourneyRecords(b);b.append(p('다른 길로 다시 가면 개구리로 출발해요. 관찰소에서 다른 조건을 고르고, 실제로 찾은 먹이 길을 나란히 살펴보세요.'));row(b,button('다른 길로 다시',()=>start('frog'),'primary'),button('발견 노트',notes),button('시작 화면',home));return;}
 const b=openDialog('쉼터에서 다시 해볼까요?','result');b.append(el('p','발견한 내용은 그대로예요','intro-target'),p('천적이 공격을 준비하면 옆으로 빠지거나 도약하세요. 풀숲을 지나가면 다음 출발점이 남아요.'));row(b,button('쉼터부터 바로 다시',()=>{retryJourney(world);closeDialog({forceResume:true});},'primary'),button('도움 설정',help));}
async function prepare(){try{assets=await loadAssets();renderer.setAssets(assets);$('asset-status').textContent='준비 완료 · 시작하기를 눌러 주세요';$('retry-assets').hidden=true;}catch(e){$('asset-status').textContent='그림을 불러오지 못했어요. 다시 시도해 주세요';$('retry-assets').hidden=false;}refreshHome();}
$('start').onclick=()=>{sound.unlock();intro();};$('retry-assets').onclick=prepare;$('entry-stages').onclick=info;$('stages').onclick=info;for(const id of ['entry-teacher','teacher','records'])$(id).onclick=notes;for(const id of ['entry-settings','help','compact-help'])$(id).onclick=help;$('checkpoint-resume').onclick=()=>start('frog');$('pause-home').onclick=home;$('resume').onclick=resume;$('pause').onclick=()=>world.paused?resume():pause();$('dialog-close').onclick=()=>{const wasLab=dialogKind==='lab';if(wasLab&&world?.phase==='at-lab'){world.phase='find-lab';world.labDismissed=true;}closeDialog({forceResume:wasLab});};dialog.oncancel=e=>{e.preventDefault();if(['result','transition','intro'].includes(dialogKind))return;const wasLab=dialogKind==='lab';if(wasLab&&world?.phase==='at-lab'){world.phase='find-lab';world.labDismissed=true;}closeDialog({forceResume:wasLab});};
window.addEventListener('keydown',e=>{if(!active||dialog.open)return;if(e.code==='Escape'){if(!e.repeat)world.paused?resume():pause();e.preventDefault();return;}if(!GAME_KEYS.has(e.code)||world.paused||world.status!=='playing')return;if(document.activeElement?.matches('input,textarea,select'))return;e.preventDefault();input.keyDown(e.code,e.repeat);});window.addEventListener('keyup',e=>input.keyUp(e.code));
function capture(n,id){try{n.setPointerCapture(id);captured.set(id,n);}catch{input.endPointer(id,true);}}
function release(e){input.endPointer(e.pointerId,e.type!=='pointerup');const n=captured.get(e.pointerId);captured.delete(e.pointerId);try{if(n?.hasPointerCapture(e.pointerId))n.releasePointerCapture(e.pointerId);}catch{}drawStick();}
function padPoint(e){const b=$('pad').getBoundingClientRect();return[e.pointerId,e.clientX-b.left-b.width/2,e.clientY-b.top-b.height/2,b.width*.34];}
$('pad').onpointerdown=e=>{e.preventDefault();if(input.startPad(...padPoint(e))){capture($('pad'),e.pointerId);drawStick();}};$('pad').onpointermove=e=>{if(input.updatePad(...padPoint(e))){e.preventDefault();drawStick();}};
for(const[id,action]of [['eat','eat'],['jump','jump']]){$(id).onpointerdown=e=>{e.preventDefault();if(input.startAction(e.pointerId,action))capture($(id),e.pointerId);};$(id).onclick=e=>{if(e.detail===0)input.queue(action);};}
for(const n of [$('pad'),$('eat'),$('jump')]){for(const t of ['pointerup','pointercancel','lostpointercapture'])n.addEventListener(t,release);n.oncontextmenu=e=>e.preventDefault();}
canvas.onpointerdown=()=>canvas.focus({preventScroll:true});
function resize(){if(resizeQueued)return;resizeQueued=true;requestAnimationFrame(()=>{resizeQueued=false;document.documentElement.style.setProperty('--app-height',`${window.visualViewport?.height??innerHeight}px`);document.documentElement.style.setProperty('--app-width',`${window.visualViewport?.width??innerWidth}px`);if(!active)return;const b=canvas.getBoundingClientRect();if(lastSize&&(Math.abs(b.width-lastSize.width)>1||Math.abs(b.height-lastSize.height)>1))pause('화면 크기가 바뀌었어요');lastSize={width:b.width,height:b.height};renderer.resize();renderer.render(world,0);});}
window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);if('ResizeObserver'in window)new ResizeObserver(resize).observe($('playfield'));window.addEventListener('blur',()=>{if(active)pause('다른 창으로 이동했어요');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause('화면을 잠시 떠났어요');});window.addEventListener('pagehide',()=>{if(lab)record.labState=lab.getState();save();if(active)pause();});
function hud(){const p=world.player,r=getJumpReadiness(world),target=selectFoodTarget(world);$('stage-label').textContent=world.role==='grasshopper'?'01 · 메뚜기의 하루':'02 · 개구리의 하루';$('food').textContent=world.fed?'한입 성공 ✓':world.role==='grasshopper'?'먹이: 식물':'먹이: 곤충';$('timer').textContent=`${Math.floor(world.time/60)}:${String(Math.floor(world.time)%60).padStart(2,'0')}`;$('escape').textContent='♥'.repeat(world.hearts)+'♡'.repeat(3-world.hearts);$('mission').textContent=world.objective;const signal=predatorSignal(world);$('state').textContent=signal.label;$('state').dataset.threat=signal.kind;$('jump').setAttribute('aria-disabled',String(!r.ready));$('jump-label').textContent=r.label;$('eat-label').textContent=p.state==='eating'?'잡았다!':world.role==='grasshopper'?p.grazeProgress>0?`${Math.floor(p.grazeProgress/.9*100)}%`:'꾹 누르기':target?'지금 먹기!':'표식 찾기';$('eat').setAttribute('aria-disabled',String(world.paused||p.state==='jumping'));$('status').textContent=signal.active?signal.detail:p.feedback?.text??(world.phase==='find-lab'?(world.labDismissed?'발견 버튼에서 관찰소를 다시 열 수 있어요':'반짝이는 관찰소로 이동해요'):world.role==='grasshopper'?'풀에서 한입 → 공격 방향을 피해 관찰소로':world.phase==='frog-return'?'관찰소로 돌아가는 길 · 천적이 어디 있는지 살펴봐요':world.fieldCondition==='absent'?'메뚜기는 없어요 · 관찰한 다른 먹이의 식물 흔적을 찾아봐요':'빠른 먹이는 높은 풀 · 느린 다른 먹이는 동쪽 낮은 풀');$('condition-label').textContent=world.fieldCondition==='absent'?'조건 B · 메뚜기 없음':world.fieldCondition==='present'?'조건 A · 두 먹이 길':'짧은 작동 체험판';$('pause').textContent=world.paused?'계속':'멈춤';}
function events(){for(const e of world.events.slice(lastEvent)){if(e.type==='ate'||e.type==='npc-ate')sound.play('eat');if(e.type==='jump')sound.play('jump');if(e.type==='predator-warning')sound.play('warning');if(e.type==='escape-used')sound.play('escape');}lastEvent=world.events.length;}
function frame(now){let dt=Math.min(.1,Math.max(0,(now-last)/1000));if(now-last>350&&active&&!world.paused)pause('실행이 잠시 중단됐어요');last=now;if(active){renderer.render(world,dt);if(!world.paused)accumulator+=dt;else accumulator=0;while(accumulator>=SETTINGS.fixedStep){stepJourney(world,input.consume(world.player),SETTINGS.fixedStep);accumulator-=SETTINGS.fixedStep;if(world.paused||world.status!=='playing')break;}events();hud();if(world.phase==='at-lab'&&!dialog.open)openLab();if(world.status!=='playing'&&!dialog.open)result();}requestAnimationFrame(frame);}
document.body.classList.add('touch-ui');refreshHome();prepare();resize();requestAnimationFrame(frame);
