/** Four connected scenes in one habitat. Arrival and exploration, never food quotas. */
import {createWorld,stepWorld,pauseWorld,addEvent,distance,clearPendingInput,canStand} from './core.js';
import {seedMeadowSnake,seedSnakeTrail,SNAKE} from './fauna/snake-rig.mjs';
import {retryJourney} from './journey.js';
const plant=(id,x,y,r=44)=>({id,x,y,r,capacity:3,bites:3,remaining:3,consumed:0});
const cover=(id,x,y,r=59)=>({id,x,y,r});
const prey=(id,role,x,y)=>({id,role,x,y,r:role==='grasshopper'?17:16,home:{x,y},alive:true,captured:false,phase:0,state:'foraging',roamRadius:90});
export const STORY_STAGES=Object.freeze([
 {id:1,title:'새 풀밭까지',role:'grasshopper',inquiry:'plant',intro:'새 풀잎을 찾아 나온 메뚜기. 저 너머 빽빽한 풀밭까지 가 보자!',goal:'새 풀밭',risk:'개구리',spawn:{x:400,y:650},end:{x:1165,y:1060},beats:[{label:'바위 옆 안전한 풀',text:'낮은 풀을 찾아가요. 안전한 풀에서 햇빛과 풀의 관계도 살펴봐요',x:555,y:560,r:60,lab:true},{label:'갈림길의 풀밭',text:'위쪽 키 큰 풀로 돌아갈까, 아래쪽 먹을 풀을 들를까?',choices:[{x:740,y:620,label:'위쪽 · 숨는 풀',id:'cover'},{x:670,y:980,label:'아래쪽 · 먹을 풀',id:'food'}],r:92},{label:'가운데 풀숲',text:'개구리의 움직임을 보며 가운데 풀숲까지 건너요',x:930,y:930,r:65},{label:'새 풀밭',text:'이제 마지막 구간! 개구리를 피해 빽빽한 새 풀밭으로',x:1165,y:1060,r:58}]},
 {id:2,title:'사냥하는 쪽도 쫓긴다',role:'frog',inquiry:'food',intro:'풀숲에 숨은 메뚜기 옆, 먹이를 놓친 그 개구리가 다른 먹이를 찾아 움직여요',goal:'물가 풀숲',risk:'뱀',spawn:{x:990,y:940},end:{x:700,y:505},beats:[{label:'물가의 안전한 풀',text:'방금 그 개구리예요. 안전한 풀에서 먹을 수 있는 것을 비교해 봐요',x:1050,y:1100,r:65,lab:true},{label:'두 먹이 길',text:'아래쪽에는 느린 애벌레, 위쪽에는 움직이는 메뚜기가 있어요',choices:[{x:670,y:1020,label:'아래쪽 · 애벌레',id:'caterpillar'},{x:780,y:650,label:'위쪽 · 메뚜기',id:'grasshopper'}],r:100},{label:'돌 옆 좁은 길',text:'뱀이 다가와요. 먹이를 더 노릴까, 다음 풀숲으로 갈까?',x:490,y:820,r:72},{label:'물가 풀숲',text:'사냥하던 개구리도 뱀의 먹이! 머리 방향을 보고 물가로 가요',x:700,y:505,r:60}]},
 {id:3,title:'달라진 풀밭',role:'frog',inquiry:'habitat',intro:'며칠 뒤, 같은 연못. 산책로 옆 풀이 베어져 먹이터와 숨을 곳이 줄었어요',goal:'남은 풀밭',risk:'오리',spawn:{x:700,y:505},end:{x:1080,y:1120},beats:[{label:'풀밭 살펴보기',text:'예전 길과 지금 길을 겹쳐 보고, 남은 풀밭을 찾아봐요',x:600,y:590,r:65,lab:true},{label:'남아 있는 먹이터',text:'베어진 옛길을 꼭 지날 필요는 없어요. 서쪽 풀숲으로 돌까, 남쪽 먹이터로 갈까?',choices:[{x:440,y:760,label:'서쪽 · 남은 풀',id:'west'},{x:705,y:1050,label:'남쪽 · 남은 먹이터',id:'south'}],r:85},{label:'남쪽 풀숲 사이',text:'오리도 애벌레를 먹어요. 남은 풀 사이의 빈터를 살피며 건너요',x:860,y:1080,r:68},{label:'남은 풀밭',text:'오리는 개구리도 먹을 수 있어요. 남아 있는 풀을 이어서 건너요',x:1080,y:1120,r:58}]},
 {id:4,title:'마지막 은신처',role:'frog',inquiry:'decomposer',intro:'해가 기울어요. 남아 있는 먹이와 풀숲을 따라 마지막 은신처로 가요',goal:'마지막 은신처',risk:'뱀',spawn:{x:1080,y:1120},end:{x:375,y:680},beats:[{label:'낙엽 아래 살펴보기',text:'안전한 풀에서 낙엽의 긴 변화를 살펴보고 출발해요',x:1120,y:1030,r:63,lab:true},{label:'마지막 먹이터',text:'먹을 것을 찾아 도약할 힘을 준비할까? 걸어서 갈 길도 있어요',x:850,y:810,r:85},{label:'탈출 갈림길',text:'숨는 풀이 있는 윗길, 가까우나 몸이 드러나는 아랫길. 어디로 갈까?',choices:[{x:620,y:585,label:'윗길 · 풀숲',id:'shelter'},{x:605,y:875,label:'아랫길 · 지름길',id:'open'}],r:80},{label:'마지막 은신처',text:'뱀의 머리와 몸통을 보고, 숨기·먹기·도약을 함께 써 봐요',x:375,y:680,r:60}]}
]);
export const STORY_RULE_NOTE='하트·점수·먹자마자 채워지는 도약 힘은 게임 규칙이에요. 실제 생물의 회복 속도와 같지 않아요.';
export const STORY_SOURCE_NOTE='교과서의 풀 → 메뚜기 → 개구리, 애벌레 → 개구리, 개구리 → 뱀과 활동지의 애벌레 → 오리, 개구리 → 오리 등을 함께 쓴 교육용 재구성이에요. 원자료의 먹이그물 한 장을 그대로 옮긴 것은 아니에요.';
function stageConfig(stage){return STORY_STAGES[Math.max(0,Math.min(3,(Number(stage)||1)-1))];}
function seedStorySnake(s){const points=[{x:s.x,y:s.y}],neck=35,r=SNAKE.turnRadius;for(let behind=2;behind<=SNAKE.bodyLength+80;behind+=2){const arc=Math.min(Math.PI*1.5,Math.max(0,behind-neck)/r),tail=Math.max(0,behind-neck-r*Math.PI*1.5);points.push(behind<=neck?{x:s.x-behind,y:s.y}:{x:s.x-neck-r*Math.sin(arc),y:s.y-r*(1-Math.cos(arc))+tail});}s.face={x:1,y:0};s.facing=1;seedSnakeTrail(s,points);}
function resetBody(p,pos){Object.assign(p,pos,{state:'idle',stateTime:0,stride:null,pose:null,tongue:null,z:0,eatCooldown:0,jumpRecovery:0,jumpCooldown:0,landingLock:0});}
export function createStory(stage=1,{previous=null,knowledge={},settings={}}={}){
 const c=stageConfig(stage),w=createWorld({stage:c.role==='grasshopper'?2:5,settings:{...settings,untimed:true}});w.story=true;w.prototype=true;w.stage=c.id;w.storyConfig=c;w.role=c.role;w.events=[];w.time=0;w.hearts=3;w.jumpEnergy=2;w.points=0;w.quota=999999;w.timed=false;w.beat=0;w.visitedShelters=[];w.knowledge={...knowledge};w.inquiryDone={};w.inquiryStates={};w.phase='journey';w.fed=false;w.scoreEligible=false;w.assisted=false;w.stageRouteChoices=[];w.fieldCondition='present';w.foodInquiryAppliedAt=null;
 let spawn={...c.spawn};
 if(stage===2&&previous?.stage===1){const actor=previous.predator;if(actor?.role==='frog'&&canStand(w,actor,w.player.r))spawn={x:actor.x,y:actor.y};w.player.id=actor?.id??'meadow-frog';w.sameFrogFrom=actor?.id??null;w.storyOrigin={x:previous.player.x,y:previous.player.y};}
 else if(c.role==='frog')w.player.id=previous?.player?.id??'meadow-frog';
 else {w.player.id='first-grasshopper';w.predator.id='meadow-frog';}
 w.spawn={...spawn};resetBody(w.player,spawn);w.checkpointPosition={...spawn};w.route=[{time:0,...spawn}];
 w.grass=[plant('west-food',430,690),plant('north-food',660,510),plant('mid-food',750,795),plant('south-food',690,1040),plant('east-food',1110,1060)];
 w.cover=[cover('start-cover',spawn.x,spawn.y,70),cover('lab-cover',c.beats[0].x,c.beats[0].y,75),cover('north-cover',735,600),cover('west-cover',440,760),cover('south-cover',690,1040),cover('middle-cover',930,930),cover('east-cover',1165,1060),cover('final-cover',c.end.x,c.end.y,78)];
 w.prey=c.role==='frog'?[prey('caterpillar-south','caterpillar',700,1040),prey('caterpillar-west','caterpillar',445,705),prey('caterpillar-east','caterpillar',1110,1070),prey('hopper-north','grasshopper',720,560),prey('hopper-middle','grasshopper',780,785)]:[prey('neighbor-hopper','grasshopper',800,850),prey('neighbor-caterpillar','caterpillar',690,1040)];
 const predPos=c.id===1?{x:925,y:860}:c.id===2?{x:760,y:860}:c.id===3?{x:850,y:990}:{x:945,y:890};Object.assign(w.predator,predPos,{home:{...predPos},state:'patrol',stateTime:0,warning:null,warningVisibleTime:0,disabled:true,facing:-1,face:{x:-1,y:0},fedNPC:false,targetNPC:null});
 if(c.id===3)w.predator={...w.predator,id:'pond-duck',role:'duck',r:35,skin:null,bodyTrail:null};if(c.id>=3){w.removedCover=w.cover.filter(x=>['north-cover','middle-cover'].includes(x.id));w.cover=w.cover.filter(x=>!['north-cover','middle-cover'].includes(x.id));w.grass=w.grass.filter(x=>!['north-food','mid-food'].includes(x.id));w.prey=w.prey.filter(x=>!['hopper-north','hopper-middle'].includes(x.id));w.mownAreas=[{x:805,y:770,rx:195,ry:155}];}
 if(c.id===4)w.cover.push(cover('last-north-cover',620,585,56));
 if(previous&&(c.id===2||c.id===4))w.grass=structuredClone(previous.grass);
 if(previous&&c.id===4)w.prey=structuredClone(previous.prey);
 if(c.id===2){Object.assign(w.predator,{x:770,y:1050,home:{x:770,y:1050},facing:1,face:{x:1,y:0}});}
 if(c.id===4)Object.assign(w.predator,{x:900,y:1000,home:{x:900,y:1000},facing:1,face:{x:1,y:0}});
 if(w.predator.role==='snake')seedStorySnake(w.predator);
 if(c.id===2&&previous){const hidden=prey('first-grasshopper','grasshopper',previous.player.x,previous.player.y);hidden.storyHidden=true;hidden.hideUntil=30;w.prey.push(hidden);}
 w.goalDestination={...c.end,r:60,label:c.goal};setBeat(w,0);addEvent(w,'story-start',{actor:w.player.id,role:w.role,storyStage:c.id,sameFrogFrom:w.sameFrogFrom??null,category:'story-event'});return w;
}
function setBeat(w,index){w.beat=index;const b=w.storyConfig.beats[index];w.routeChoices=b.choices?.map(x=>({...x}))??[];if(w.stage===2&&w.fieldCondition==='absent')w.routeChoices=w.routeChoices.map(x=>x.id==='grasshopper'?{...x,label:'위쪽 · 메뚜기가 없어요'}:x);w.destination=b.choices?{...b.choices[0],r:b.r,label:b.label}:{x:b.x,y:b.y,r:b.r,label:b.label};w.objective=b.text;w.beatStart=w.time;w.beatFoodStart=w.player.eaten;w.lab=b.lab?{x:b.x,y:b.y,r:b.r}:null;addEvent(w,'story-beat',{beat:index,label:b.label,category:'story-event'});if(index>=1)w.predator.disabled=false;}
export function storyMission(w){const b=w.storyConfig.beats[w.beat];return{title:`${w.stage}/4 · ${w.storyConfig.title}`,progress:`${w.beat+1}/4 ${b.label}  ·  마지막: ${w.storyConfig.goal}`,next:w.stage===2&&w.fieldCondition==='absent'&&w.beat>=1?'먹이터에 메뚜기가 없는 조건이에요. 관찰한 애벌레 먹이 길을 찾아볼까요?':b.text,beacon:w.destination};}
export function openStoryInquiry(w){if(!w.story)return false;w.inquiryKind=w.storyConfig.inquiry;w.inquiryReturnPhase=w.phase;w.phase='at-inquiry';pauseWorld(w,true);addEvent(w,'inquiry-open',{kind:w.inquiryKind,position:{x:w.player.x,y:w.player.y},category:'model-rule'});return true;}
export function returnFromStoryInquiry(w,evidence=null){if(!w.story)return false;const kind=w.storyConfig.inquiry;if(evidence){w.knowledge[kind]=structuredClone(evidence);if(kind==='food'){w.fieldCondition=evidence.fieldCondition==='absent'?'absent':'present';for(const q of w.prey)if(q.role==='grasshopper'&&!q.storyHidden){if(w.fieldCondition==='absent'&&q.alive){q.alive=false;q.captured=false;q.removedByCondition=true;}else if(w.fieldCondition==='present'&&q.removedByCondition){q.alive=true;q.removedByCondition=false;}}if(w.beat>0){w.routeChoices=(w.storyConfig.beats[w.beat].choices??[]).map(x=>({...x,label:x.id==='grasshopper'&&w.fieldCondition==='absent'?'위쪽 · 메뚜기가 없어요':x.label}));}w.foodInquiryAppliedAt=w.time;addEvent(w,'field-condition',{condition:w.fieldCondition,category:'model-rule'});}if(kind==='habitat'&&Array.isArray(evidence.worldRoute)){w.plannedRoute=evidence.worldRoute.map(p=>({x:p.x,y:p.y}));w.plannedChoice=evidence.routeChoice;}if(!w.inquiryDone[kind])w.points+=100;w.inquiryDone[kind]=true;addEvent(w,'inquiry-complete',{kind,observations:evidence.observations,position:{x:w.player.x,y:w.player.y},category:'model-observation'});}w.phase='journey';w.immuneUntil=w.time+3;w.checkpointPosition={x:w.player.x,y:w.player.y};if(w.beat===0)setBeat(w,1);clearPendingInput(w);pauseWorld(w,false);addEvent(w,'inquiry-return',{kind,completed:Boolean(evidence),position:{x:w.player.x,y:w.player.y},category:'model-rule'});return true;}
function completeBeat(w,b){const selected=b.choices?.find(x=>distance(w.player,x)<b.r);if(selected){w.stageRouteChoices.push(selected.id);if(w.stage===3&&selected.id===w.plannedChoice)addEvent(w,'finding-used',{kind:'habitat',choice:selected.id,position:{x:w.player.x,y:w.player.y},category:'observed-game-event'});addEvent(w,'route-choice',{choice:selected.id,beat:w.beat,position:{x:w.player.x,y:w.player.y}});}addEvent(w,'story-landmark',{beat:w.beat,label:b.label,position:{x:w.player.x,y:w.player.y}});w.points+=100;w.checkpointPosition={x:w.player.x,y:w.player.y};
 if(b.lab){openStoryInquiry(w);return;}if(w.beat===3){w.status='success';w.goalReached=true;w.reason='은신처 도착';w.result={completed:true,total:w.points+300,stars:0,eligible:false};w.points+=300;clearPendingInput(w);addEvent(w,'story-arrival',{position:{x:w.player.x,y:w.player.y},goal:w.storyConfig.goal,points:w.points});if(w.stage===1){w.hiddenHopper={x:w.player.x,y:w.player.y,id:w.player.id};addEvent(w,'hopper-hid',{actor:w.player.id,target:w.predator.id,position:{x:w.player.x,y:w.player.y},category:'story-event'});}return;}
 setBeat(w,w.beat+1);w.player.feedback={text:`${w.storyConfig.beats[w.beat].label}으로!`,until:w.time+3};}
export function stepStory(w,input={},dt=1/60){const before=w.events.length;stepWorld(w,input,dt);if(w.paused||w.status!=='playing')return;
 for(const e of w.events.slice(before))if(e.type==='ate'&&e.actor===w.player.id){if((w.stage===1&&e.food==='grass'&&w.knowledge.plant)||(w.stage===2&&['grasshopper','caterpillar'].includes(e.food)&&w.knowledge.food&&w.foodInquiryAppliedAt!==null))addEvent(w,'finding-used',{kind:w.storyConfig.inquiry,food:e.food,condition:w.stage===2?w.fieldCondition:undefined,position:{...e.position},category:'observed-game-event'});}
 for(const c of w.cover){if(distance(w.player,c)<c.r*.55&&!w.visitedShelters.includes(c.id)){w.visitedShelters.push(c.id);w.checkpointPosition={x:c.x,y:c.y};addEvent(w,'shelter-checkpoint',{shelter:c.id,position:{x:c.x,y:c.y}});}}
 if(w.stage===3&&!w.oldPathSeen&&distance(w.player,{x:925,y:900})<125){w.oldPathSeen=true;addEvent(w,'changed-habitat-observed',{position:{x:w.player.x,y:w.player.y},observed:true});}
 const b=w.storyConfig.beats[w.beat],close=b.choices?b.choices.some(x=>distance(w.player,x)<b.r):distance(w.player,b)<b.r;if(close&&w.player.state!=='jumping')completeBeat(w,b);
}
export function retryStory(w){retryJourney(w);w.jumpEnergy=Math.max(1,w.jumpEnergy??0);w.phase='journey';clearPendingInput(w);return w;}
export function storyRecord(w){const names={grass:'풀',grasshopper:'메뚜기',caterpillar:'애벌레',frog:'개구리',snake:'뱀',duck:'오리'};return{stage:w.stage,title:w.storyConfig.title,fieldCondition:w.stage===2?w.fieldCondition:null,points:w.points,seconds:Math.round(w.time),routes:[...w.stageRouteChoices],foods:w.events.filter(e=>e.type==='ate'&&e.actor===w.player.id).map(e=>`${names[e.food]} → ${names[e.eater]}`),observed:w.events.filter(e=>e.type==='npc-ate'&&e.observed).map(e=>`${names[e.food]} → ${names[e.eater]}`),captures:w.events.filter(e=>e.type==='capture').length,inquiry:Boolean(w.inquiryDone[w.storyConfig.inquiry]),events:w.events.filter(e=>['ate','npc-ate','capture','inquiry-complete','finding-used','route-choice','story-arrival'].includes(e.type)).map(e=>({...e}))};}
export function serializeStory(w){if(!w?.story)return null;return{stage:w.stage,beat:w.beat,fieldCondition:w.fieldCondition,foodInquiryAppliedAt:w.foodInquiryAppliedAt,hearts:w.hearts,jumpEnergy:w.jumpEnergy,points:w.points,time:w.time,player:{x:w.player.x,y:w.player.y,id:w.player.id,eaten:w.player.eaten},checkpointPosition:{...w.checkpointPosition},grass:structuredClone(w.grass),prey:structuredClone(w.prey),events:structuredClone(w.events),route:structuredClone(w.route),knowledge:structuredClone(w.knowledge),inquiryDone:{...w.inquiryDone},inquiryStates:structuredClone(w.inquiryStates),visitedShelters:[...w.visitedShelters],stageRouteChoices:[...w.stageRouteChoices],phase:w.phase,status:w.status,sameFrogFrom:w.sameFrogFrom??null};}
export function restoreStory(saved,{settings={}}={}){if(!saved||!Number.isInteger(saved.stage)||saved.stage<1||saved.stage>4)return null;const w=createStory(saved.stage,{knowledge:saved.knowledge??{},settings});if(!Number.isInteger(saved.beat)||saved.beat<0||saved.beat>3||!canStand(w,saved.player??{},w.player.r))return null;for(const key of ['grass','prey','events','route','knowledge','inquiryDone','inquiryStates','visitedShelters','stageRouteChoices'])if(saved[key])w[key]=structuredClone(saved[key]);w.beat=saved.beat;w.time=Math.max(0,Number(saved.time)||0);w.points=Math.max(0,Number(saved.points)||0);w.hearts=Math.max(1,Math.min(3,Number(saved.hearts)||3));w.jumpEnergy=Math.max(0,Math.min(3,Number(saved.jumpEnergy)||0));resetBody(w.player,saved.player);for(const q of w.prey)if(q.captured){q.captured=false;q.state='foraging';}w.player.eaten=Math.max(0,Number(saved.player.eaten)||0);w.fed=w.player.eaten>0;w.sameFrogFrom=saved.sameFrogFrom;w.fieldCondition=saved.fieldCondition==='absent'?'absent':'present';w.foodInquiryAppliedAt=Number.isFinite(saved.foodInquiryAppliedAt)?saved.foodInquiryAppliedAt:null;if(w.stage===3&&w.knowledge.habitat?.worldRoute){w.plannedRoute=structuredClone(w.knowledge.habitat.worldRoute);w.plannedChoice=w.knowledge.habitat.routeChoice;}w.checkpointPosition=canStand(w,saved.checkpointPosition??{},w.player.r)?saved.checkpointPosition:{...w.spawn};setBeat(w,w.beat);w.phase=saved.phase==='at-inquiry'?'at-inquiry':'journey';w.inquiryKind=w.storyConfig.inquiry;if(saved.status==='failed'){resetBody(w.player,w.checkpointPosition);w.hearts=3;w.jumpEnergy=Math.max(1,w.jumpEnergy);}w.immuneUntil=w.time+3;w.paused=true;return w;}
