import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {installDom} from '../qa/campaign-dom-harness.mjs';

test('real main module boot, optional teacher, intro, play, interruption, retry and stage selection event flows',async()=>{
 const h=installDom();await import('../src/main.js?campaign-ui');await h.settle();h.frames(2);
 assert.equal(h.el('start').disabled,false,h.el('asset-status').textContent);
 h.click('entry-teacher');assert.equal(h.el('dialog').open,true);assert.match(h.el('dialog-content').textContent,/선택 활동/);assert.equal(h.el('game').hidden,true);
 h.findButton('선택 질문 A–F').click();assert.match(h.el('dialog-content').textContent,/잠그지 않습니다/);h.click('dialog-close');assert.equal(h.el('dialog').open,false);
 h.click('start');assert.match(h.el('dialog-title').textContent,/1단계/);assert.ok(h.findButton('출발!'));assert.equal(h.el('dialog-content').querySelectorAll('textarea').length,0);h.findButton('출발!').click();h.frames(3);assert.equal(h.el('entry').hidden,true);assert.equal(h.el('game').hidden,false);assert.equal(h.el('dialog').open,false);
 h.key('KeyJ');h.frames(130);h.key('KeyJ','keyup');assert.match(h.el('food').textContent,/먹이 1 \/ 4/);
 h.key('KeyD');h.frames(40);h.key('KeyD','keyup');h.click('pause');h.frames(2);const paused=h.el('timer').textContent;h.frames(60);assert.equal(h.el('timer').textContent,paused);assert.equal(h.el('pause-overlay').hidden,false);h.click('resume');h.frames(2);assert.equal(h.el('pause-overlay').hidden,true);
 h.click('help');const settingsTimer=h.el('timer').textContent;h.frames(60);assert.equal(h.el('timer').textContent,settingsTimer);h.click('dialog-close');h.frames(80);assert.notEqual(h.el('timer').textContent,settingsTimer);
 h.resize(390,448);h.frames(2);assert.equal(h.el('pause-overlay').hidden,false);assert.match(h.el('pause-reason').textContent,/크기/);h.click('teacher');h.findButton('게임 기록').click();assert.match(h.el('dialog-content').textContent,/섭식|먹기|메뚜기/);h.click('dialog-close');assert.equal(h.el('pause-overlay').hidden,false);h.click('resume');h.frames(2);
 h.window.dispatchEvent({type:'blur'});h.frames(2);const record=h.latestRun();assert.ok(record.time>0);assert.ok(record.events.some(e=>e.type==='ate'));h.click('resume');h.frames(2);
 h.click('stages');assert.equal(h.el('dialog-content').querySelectorAll('button').filter(b=>/^\d\./.test(b.textContent)).length,6);h.findButton('4.').click();h.findButton('출발!').click();h.frames(2);assert.match(h.el('stage-label').textContent,/4 \/ 6/);assert.match(h.el('food').textContent,/0 \/ 6입/);
 // The starting grass patch is reachable and holding eat works through real DOM key handlers.
 h.key('KeyJ');h.frames(120);h.key('KeyJ','keyup');assert.match(h.el('food').textContent,/먹이 [12] \/ 6입/);
 h.frames(1250,100);assert.match(h.el('dialog-title').textContent,/한 번 더/);assert.ok(h.findButton('다시 도전'));assert.ok(h.findButton('이어 체험'));h.click('dialog-close');assert.equal(h.el('dialog').open,false);h.click('pause');assert.match(h.el('dialog-title').textContent,/한 번 더/);h.findButton('다시 도전').click();h.frames(2);assert.match(h.el('food').textContent,/0 \/ 6입/);assert.equal(h.el('timer').textContent,'120초');
 h.click('teacher');h.click('dialog-close');h.frames(2);assert.equal(h.el('dialog').open,false);h.key('KeyJ');h.frames(120);h.key('KeyJ','keyup');h.frames(1250,100);const foodBefore=h.el('food').textContent;h.findButton('이어 체험').click();h.frames(2);assert.equal(h.el('food').textContent,foodBefore);assert.equal(h.el('timer').textContent,'시간 제한 없음');h.click('help');const untimed=h.el('dialog-content').querySelectorAll('input').find(x=>x.parentElement.textContent.includes('시간 제한 없이'));untimed.checked=true;untimed.dispatchEvent({type:'change'});untimed.checked=false;untimed.dispatchEvent({type:'change'});h.click('dialog-close');h.frames(2);assert.equal(h.el('timer').textContent,'시간 제한 없음');
 h.click('stages');h.findButton('1.').click();h.findButton('출발!').click();h.frames(2);h.el('pad').dispatchEvent({type:'pointerdown',pointerId:1,pointerType:'touch',clientX:90,clientY:56});h.el('eat').dispatchEvent({type:'pointerdown',pointerId:2,pointerType:'touch'});h.el('jump').dispatchEvent({type:'pointerdown',pointerId:3,pointerType:'touch'});h.frames(2);assert.equal(h.el('jump-label').textContent,'착지 후 준비');h.el('pad').dispatchEvent({type:'pointercancel',pointerId:1,pointerType:'touch'});h.el('eat').dispatchEvent({type:'pointercancel',pointerId:2,pointerType:'touch'});h.frames(620);h.window.dispatchEvent({type:'blur'});const touchRun=h.latestRun();assert.equal(touchRun.events.filter(e=>e.type==='jump').length,1);h.el('jump').dispatchEvent({type:'pointercancel',pointerId:3,pointerType:'touch'});assert.equal(h.el('jump').captures.size,0);assert.ok(h.canvasCalls>1000);
 fs.writeFileSync(new URL('../qa/campaign-dom-report.json',import.meta.url),JSON.stringify({method:'Real main.js module graph and event listeners with mocked DOM/RAF/Canvas call surface; real native-decoded image files. Not browser layout or physical touch QA.',passed:['asset loading','optional teacher from home','no-question intro','keyboard eating','move/pause/resume','settings freezing','resize explicit pause','teacher return preserves prior pause','blur archive','all six stage choices','grasshopper held eating','timeout failure','full retry','teacher close returns to same live game','closed result reopens','continue preserves food and stays untimed through settings','three-finger DOM pointer ownership','held jump never repeats','pointer cancellation releases capture'],canvasCalls:h.canvasCalls},null,2));
});

test('storage reset failure keeps live state and explains failure; successful retry clears records',async()=>{
 const progress={version:1,completed:{1:true},bestScores:{1:900},stars:{1:3},conditions:{1:{assisted:false}}};
 const h=installDom({saved:{'eat-and-escape-v1:progress':JSON.stringify(progress)}});await import('../src/main.js?campaign-reset');await h.settle();h.frames(2);assert.match(h.el('completion-summary').textContent,/1 \/ 6/);h.click('start');h.findButton('출발!').click();h.frames(2);h.click('help');h.findButton('새 학생용으로 기록 비우기').click();const remove=globalThis.localStorage.removeItem;globalThis.localStorage.removeItem=()=>{throw new Error('Storage deletion denied');};h.findButton('기록 비우기').click();assert.match(h.el('dialog-title').textContent,/모두 지우지 못했어요/);assert.match(h.el('dialog-content').textContent,/삭제 완료로 처리하지 않았습니다/);assert.equal(h.el('entry').hidden,true);assert.equal(h.el('game').hidden,false);assert.deepEqual(JSON.parse(h.data.get('eat-and-escape-v1:progress')),progress);globalThis.localStorage.removeItem=remove;h.findButton('설정으로 돌아가기').click();h.findButton('새 학생용으로 기록 비우기').click();h.findButton('기록 비우기').click();assert.equal(h.el('entry').hidden,false);assert.equal(h.el('game').hidden,true);assert.equal(h.el('dialog').open,false);assert.match(h.el('completion-summary').textContent,/0 \/ 6/);assert.equal(h.data.has('eat-and-escape-v1:progress'),false);
 fs.writeFileSync(new URL('../qa/campaign-reset-report.json',import.meta.url),JSON.stringify({checkedAt:new Date().toISOString(),version:'1.0.1',mockedDom:true,failureMessageHonest:true,failurePreservesLiveState:true,successAfterRetryClearsRecords:true},null,2));
});
