import test from 'node:test';import assert from 'node:assert/strict';import {createWorld,stepWorld,requestEat,requestJump,canStand}from'../src/core.js';import{STRIDE}from'../src/locomotion.js';import{ART}from'../src/motion.js';
const free=()=>{const w=createWorld({timed:false});w.navigation=null;w.rocks=[];w.prey=[];w.predator.disabled=true;return w;};
for(const dir of[{x:1,y:0},{x:-1,y:0},{x:0,y:-1},{x:0,y:1},{x:.7071067811865475,y:.7071067811865475}])test(`ground hop ${dir.x},${dir.y} moves only while all contacts are airborne`,()=>{const w=free();let prior={...w.player},moved=0,planted=0;for(let i=0;i<30;i++){stepWorld(w,{move:dir});const p=w.player;if(p.pose){assert.equal(p.pose.diagnostics.ikClamps.length,0);const live=Object.values(p.pose.contacts).some(c=>c.planted);if(live){if(prior.pose&&Object.values(prior.pose.contacts).some(c=>c.planted))assert.ok(Math.hypot(p.x-prior.x,p.y-prior.y)<1e-6);planted++;}else if(Math.hypot(p.x-prior.x,p.y-prior.y)>0)moved++;}prior={...p};}assert.ok(moved>5);assert.ok(planted>6);assert.ok(Math.abs(Math.hypot(w.player.x-580,w.player.y-900)-STRIDE.distance)<1e-6);assert.equal(w.player.z,0);});
test('a released direction completes landing with no midair facing flip',()=>{const w=free();for(let i=0;i<12;i++)stepWorld(w,{move:{x:1,y:0}});const x=w.player.x;for(let i=0;i<18;i++){stepWorld(w,{move:{x:-1,y:0}});assert.equal(w.player.facing,1);}assert.ok(w.player.x>x);stepWorld(w,{move:{x:-1,y:0}});assert.equal(w.player.facing,-1);});
test('a valid ground action starts within one tick without queued locomotion delay',()=>{const w=free();for(let i=0;i<12;i++)stepWorld(w,{move:{x:0,y:1}});requestEat(w);assert.equal(w.player.state,'eating');assert.equal(w.player.stride,null);assert.equal(w.player.z,0);assert.equal(w.events.filter(e=>e.type==='eat-start').length,1);});
test('pause freezes a locomotion reservation and touchdown resumes once',()=>{const w=free();for(let i=0;i<13;i++)stepWorld(w,{move:{x:0,y:-1}});const p=JSON.stringify(w.player);w.paused=true;for(let i=0;i<100;i++)stepWorld(w,{move:{x:1,y:0}});assert.equal(JSON.stringify(w.player),p);w.paused=false;for(let i=0;i<17;i++)stepWorld(w);assert.equal(w.player.state,'idle');assert.equal(w.player.z,0);});
test('a ground hop shortens before an obstacle and never enters it',()=>{const w=free();w.rocks=[{x:640,y:900,r:7}];for(let i=0;i<120;i++){stepWorld(w,{move:{x:1,y:0}});assert.ok(canStand(w,w.player,w.player.r));}assert.ok(w.player.x<=599.0001);});
test('timed end clears an in-flight stride and pending actions',()=>{const w=free();for(let i=0;i<12;i++)stepWorld(w,{move:{x:0,y:1}});requestJump(w,{x:1,y:0});w.timed=true;w.time=89.99;stepWorld(w);assert.equal(w.status,'failed');assert.equal(w.player.stride,null);assert.equal(w.player.pendingAction,null);assert.equal(w.player.pose,null);assert.equal(w.player.z,0);});
test('tap before takeoff makes a precise shorter hop while retaining planted feet',()=>{const w=free();for(let i=0;i<4;i++)stepWorld(w,{move:{x:1,y:0}});for(let i=0;i<26;i++)stepWorld(w);assert.ok(Math.abs(w.player.x-580-STRIDE.distance*.28)<1e-7);assert.equal(w.player.z,0);});
