import test from 'node:test';import assert from 'node:assert/strict';
import {createStorage,SAVE_PREFIX,runRecord,upsertRun} from '../src/storage.js';import {createAudio,SOUND_CUES} from '../src/audio.js';
const fake=()=>{const map=new Map();return{map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
test('versioned save sections are independent and local',()=>{const s=fake(),v=createStorage(s);v.write('progress',{completed:{1:true}});v.write('activities',{answer:'reason'});assert.deepEqual(v.read('progress',{}),{completed:{1:true}});assert.deepEqual(v.read('activities',{}),{answer:'reason'});assert.equal(s.map.size,2);assert.ok([...s.map.keys()].every(k=>k.startsWith(SAVE_PREFIX)));});
test('corrupted or blocked storage reports failure without crashing play',()=>{let errors=0;const s=fake(),v=createStorage(s,()=>errors++);s.map.set(SAVE_PREFIX+'progress','bad');assert.deepEqual(v.read('progress',{completed:{}}),{completed:{}});assert.equal(errors,1);const b=createStorage({setItem(){throw Error('quota');}},()=>errors++);assert.equal(b.write('runs',[1]),false);assert.equal(errors,2);assert.equal(createStorage(null).write('x',{}),false);});
test('run snapshots keep every event and replacing a snapshot avoids duplicated runs',()=>{const w={stage:1,segment:0,role:'frog',status:'playing',time:20,settings:{},events:Array.from({length:500},(_,i)=>({type:'ate',target:`q${i}`}))},a=runRecord(w,'one');let runs=upsertRun([],a);w.events.push({type:'capture'});runs=upsertRun(runs,runRecord(w,'one'));assert.equal(runs.length,1);assert.equal(runs[0].events.length,501);assert.equal(a.events.length,500);});
test('sound never initializes or plays before a user gesture unlock',()=>{let made=0;class C{constructor(){made++;this.state='running';this.currentTime=1;this.destination={};}createGain(){return{gain:{value:0},connect(){}}}}const sound=createAudio({AudioContext:C});assert.equal(sound.play('eat'),false);assert.equal(made,0);assert.equal(sound.unlock(),true);assert.equal(made,1);sound.unlock();assert.equal(made,1);});
test('mute and unsupported audio stay safe',()=>{const sound=createAudio({AudioContext:null});assert.equal(sound.unlock(),false);assert.equal(sound.play('success'),false);sound.stop();sound.setMuted(true);sound.setVolume(999);assert.ok(Object.keys(SOUND_CUES).includes('warning'));});
test('all sound cues are finite short original synthesis notes',()=>{for(const notes of Object.values(SOUND_CUES))for(const[n,f,d,type]of notes){assert.ok(n>=0&&n<1);assert.ok(f>=100&&f<2000);assert.ok(d>0&&d<.5);assert.ok(['sine','triangle'].includes(type));}});
