/** Pure campaign metadata and save-state helpers. Gameplay completion is never an assessment. */
const stageRows=[
 {id:1,title:'첫 한입',role:'frog',quota:4,timeLimit:90,grasshoppers:8,caterpillars:0,grassBites:0,destinationLabel:'물가 쉼터',foodLabel:'메뚜기',predatorLabel:'뱀',description:'메뚜기 4마리를 먹고 물가 쉼터로 가요'},
 {id:2,title:'이번에는 메뚜기',role:'grasshopper',quota:6,timeLimit:120,grasshoppers:0,caterpillars:0,grassBites:12,destinationLabel:'반대편 풀숲',foodLabel:'풀',predatorLabel:'개구리',description:'풀 6입을 먹고 반대편 풀숲으로 가요'},
 {id:3,title:'어느 먹이를 노릴까',role:'frog',quota:6,timeLimit:120,grasshoppers:6,caterpillars:8,grassBites:0,destinationLabel:'물가 쉼터',foodLabel:'곤충',predatorLabel:'뱀',description:'메뚜기와 애벌레 중 곤충 6마리를 먹고 쉼터로 가요'},
 {id:4,title:'숨을 곳이 줄었다',role:'grasshopper',quota:6,timeLimit:120,grasshoppers:0,caterpillars:0,grassBites:12,destinationLabel:'반대편 풀숲',foodLabel:'풀',predatorLabel:'개구리',description:'은신처 두 곳이 줄었어요. 풀 6입을 먹고 같은 풀숲으로 가요'},
 {id:5,title:'먹이 길이 달라졌다',role:'frog',quota:6,timeLimit:150,grasshoppers:2,caterpillars:8,grassBites:0,destinationLabel:'물가 쉼터',foodLabel:'곤충',predatorLabel:'뱀',description:'메뚜기는 2마리, 애벌레는 8마리. 곤충 6마리를 먹고 쉼터로 가요'},
 {id:6,title:'두 생물의 하루',role:'frog',quota:3,timeLimit:75,grasshoppers:3,caterpillars:4,grassBites:0,destinationLabel:'물가 쉼터',foodLabel:'곤충',predatorLabel:'뱀',description:'개구리로 3마리 먹고, 다른 메뚜기로 풀 4입 먹고 도착해요'}
];
export const STAGES=Object.freeze(stageRows.map(s=>Object.freeze({...s,stage:s.id,fastTime:s.timeLimit*.6})));
export function getStage(stage=1,segment=0){const index=Math.max(1,Math.min(6,Math.floor(Number(stage)||1)));const s=STAGES[index-1];if(index===6&&Number(segment)===1)return{...s,segment:1,role:'grasshopper',quota:4,grasshoppers:0,caterpillars:0,grassBites:9,destinationLabel:'반대편 풀숲',foodLabel:'풀',predatorLabel:'개구리'};return{...s,segment:0};}
export function normalizeSettings(s={}){return{assistance:Boolean(s.assistance),untimed:Boolean(s.untimed||s.assistance),slowPredators:Boolean(s.slowPredators||s.assistance),longWarning:Boolean(s.longWarning||s.assistance),largeButtons:Boolean(s.largeButtons),reducedMotion:Boolean(s.reducedMotion),eatHold:s.eatHold!==false};}
export function isAssisted(s={}){return Boolean(s.assistance||s.untimed||s.slowPredators||s.longWarning);}
export function scoreSegment({success=true,eaten=0,quota=0,elapsed=0,timeLimit=90,fastTime=timeLimit*.6,escapeUsed=false,eligible=true}={}){const complete=Boolean(success&&eaten>=quota),base=complete?600:0,escape=complete&&!escapeUsed?100:0,extra=complete?Math.min(2,Math.max(0,eaten-quota))*50:0,time=complete?Math.max(0,Math.min(200,Math.floor(200*Math.max(0,timeLimit-elapsed)/(timeLimit-fastTime)+1e-9))):0,total=base+escape+extra+time;return{eligible:Boolean(eligible&&complete),completed:complete,total,stars:eligible&&complete?(total>=900?3:total>=800?2:1):0,base,escape,extra,time,reason:!complete?'목표와 도착을 모두 마쳐야 기록해요':!eligible?'완료는 같은 기쁨으로 인정해요. 이번 조건은 기본 최고점과 따로 남겨요':'기본 도전 기록'};}
export function createProgress(value={}){return{version:1,completed:{...(value.completed??{})},bestScores:{...(value.bestScores??{})},stars:{...(value.stars??{})},conditions:{...(value.conditions??{})}};}
export function campaignComplete(progress){return STAGES.every(s=>Boolean(progress?.completed?.[s.id]));}
export function recordCompletion(progress,w){const next=createProgress(progress);if(w.status!=='success'||!w.result?.completed)return next;next.completed[w.stage]=true;next.conditions[w.stage]={assisted:Boolean(w.assisted),continued:Boolean(w.continued),segmentRetry:Boolean(w.segmentRetry)};if(w.result.eligible){next.bestScores[w.stage]=Math.max(next.bestScores[w.stage]??0,w.result.total);next.stars[w.stage]=Math.max(next.stars[w.stage]??0,w.result.stars);}return next;}
