/** Deterministic simulation. Approved animation phase owns the action clock. */
import {ART,RIGS,EAT_DURATION,hopPose,tongueGeometry,targetPoint,facing} from './motion.js';
import {NAV} from './navigation.js';
import {getStage,normalizeSettings,isAssisted,scoreSegment} from './campaign.js';
import {MOUTH} from './vendor/tongue-v10.mjs';
import {STRIDE,stridePose,strideProgress} from './locomotion.js';
import {GAME_EAT} from './tongue-gameplay.js';
import {stepPreyMotion} from './fauna/prey-behavior.mjs';
import {updateSnakeTrail,seedMeadowSnake,SNAKE} from './fauna/snake-rig.mjs';
export const SETTINGS=Object.freeze({fixedStep:1/60,maxFrameDelta:.1,worldWidth:1672,worldHeight:941/.62,roundSeconds:90,moveSpeed:105,jumpSeconds:RIGS.big.duration,jumpRecovery:6,landingLock:2.5,grassBiteSeconds:.9,inputDeadzone:.18,attackHeight:46,jumpHeight:840*ART.scale,eatSeconds:EAT_DURATION,eatCooldown:EAT_DURATION+.18,tongueReach:160,windupSeconds:1.2,attackSeconds:.35,predatorRecovery:2.1});
export const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
export const length=v=>Math.hypot(v.x,v.y);
export function normalize(v){const l=length(v);return l?{x:v.x/l,y:v.y/l}:{x:0,y:0};}
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function random(seed=17){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function segmentHitsCircle(a,b,c,r=c.r){const dx=b.x-a.x,dy=b.y-a.y,den=dx*dx+dy*dy,t=den?clamp(((c.x-a.x)*dx+(c.y-a.y)*dy)/den,0,1):0;return Math.hypot(a.x+dx*t-c.x,a.y+dy*t-c.y)<=r;}
export function pointInPolygon(p,polygon){let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>p.y)!==(b[1]>p.y)&&p.x<(b[0]-a[0])*(p.y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function ellipseHit(a,b,o,pad=0){const rx=(o.rx??o.r)+pad,ry=(o.ry??o.r)+pad;return segmentHitsCircle({x:(a.x-o.x)/rx,y:(a.y-o.y)/ry},{x:(b.x-o.x)/rx,y:(b.y-o.y)/ry},{x:0,y:0,r:1});}
function distanceSegment(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],d=dx*dx+dy*dy,t=d?clamp(((p.x-a[0])*dx+(p.y-a[1])*dy)/d,0,1):0;return Math.hypot(p.x-a[0]-dx*t,p.y-a[1]-dy*t);}
function edges(poly,fn){return poly.some((a,i)=>fn(a,poly[(i+1)%poly.length]));}
function cross(a,b,c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);}
function segmentsCross(a,b,c,d){return cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0&&Math.max(Math.min(a.x,b.x),Math.min(c.x,d.x))<=Math.min(Math.max(a.x,b.x),Math.max(c.x,d.x))+1e-9&&Math.max(Math.min(a.y,b.y),Math.min(c.y,d.y))<=Math.min(Math.max(a.y,b.y),Math.max(c.y,d.y))+1e-9;}
function polygonLine(a,b,poly){return pointInPolygon(a,poly)||pointInPolygon(b,poly)||edges(poly,(c,d)=>segmentsCross(a,b,{x:c[0],y:c[1]},{x:d[0],y:d[1]}));}
const worldPoly=poly=>poly.map(([x,y])=>[x,y/ART.groundY]);
export function blockedLine(w,a,b){return w.rocks.some(r=>r.polygon?polygonLine(a,b,r.polygon):ellipseHit(a,b,r));}
export function canStand(w,p,r){
 if(p.x<r||p.y<r||p.x>w.width-r||p.y>w.height-r)return false;
 if(w.rocks.some(o=>o.polygon?(pointInPolygon(p,o.polygon)||edges(o.polygon,(a,b)=>distanceSegment(p,a,b)<r)):ellipseHit(p,p,o,r)))return false;
 if(w.navigation){const meadow=w.navigation.worldMeadow??worldPoly(w.navigation.meadow),water=w.navigation.worldWater??worldPoly(w.navigation.water??[]);if(!pointInPolygon(p,meadow)||edges(meadow,(a,b)=>distanceSegment(p,a,b)<r))return false;if(water.length&&(pointInPolygon(p,water)||edges(water,(a,b)=>distanceSegment(p,a,b)<r)))return false;}return true;
}
function segmentDistance(a,b,c,d){const cp={x:c[0],y:c[1]},dp={x:d[0],y:d[1]};if(segmentsCross(a,b,cp,dp))return 0;return Math.min(distanceSegment(a,c,d),distanceSegment(b,c,d),distanceSegment(cp,[a.x,a.y],[b.x,b.y]),distanceSegment(dp,[a.x,a.y],[b.x,b.y]));}
/** Exact swept disc against polygon edges, including a tiny concave tangent interval. */
export function clearGroundPath(w,start,end,r=start.r){
 if(!canStand(w,start,r)||!canStand(w,end,r))return false;
 const touches=poly=>edges(poly,(a,b)=>segmentDistance(start,end,a,b)<r-1e-8);
 if(w.rocks.some(o=>o.polygon?(polygonLine(start,end,o.polygon)||touches(o.polygon)):ellipseHit(start,end,o,r)))return false;
 if(w.navigation){const m=w.navigation.worldMeadow??worldPoly(w.navigation.meadow),water=w.navigation.worldWater??worldPoly(w.navigation.water??[]);if(touches(m)||water.length&&(polygonLine(start,end,water)||touches(water)))return false;}return true;
}
/** Axis-separated movement permits sliding but each sub-segment is itself swept. */
export function moveBody(w,b,dx,dy){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/Math.max(2,b.r/3)));for(let i=0;i<steps;i++){const nx=clamp(b.x+dx/steps,b.r,w.width-b.r);if(clearGroundPath(w,b,{x:nx,y:b.y},b.r))b.x=nx;const ny=clamp(b.y+dy/steps,b.r,w.height-b.r);if(clearGroundPath(w,b,{x:b.x,y:ny},b.r))b.y=ny;}}
export function clearLeapPath(w,p,dx){return clearGroundPath(w,p,{x:p.x+dx,y:p.y},p.r);}
/** Each stage is a finite, deterministic population; background competitors consume zero. */
export function createWorld({stage=1,segment=0,seed=17,settings={},timed,checkpoint=null,segmentRetry=false}={}){
 const config=getStage(stage,segment),options=normalizeSettings({...settings,...(timed===false?{untimed:true}:{})}),rng=random(seed),role=config.role;
 const spawn=role==='frog'?{x:580,y:900}:{x:400,y:650};
 const p={id:`${role}-player`,role,...spawn,r:role==='frog'?34:19,face:{x:1,y:0},facing:1,z:0,state:'idle',stateTime:0,eatCooldown:0,jumpCooldown:0,jumpRecovery:0,landingLock:0,jumpDuration:RIGS.big.duration,jumpDirection:{x:1,y:0},jumpKind:'big',pose:null,tongue:null,eaten:0,grazeProgress:0,feedback:null};
 const allHoppers=[targetPoint(p),{x:530,y:760},{x:440,y:620},{x:830,y:810},{x:1000,y:1020},{x:1125,y:1000},{x:665,y:560},{x:910,y:695}];
 const caterpillars=[{x:410,y:520},{x:520,y:460},{x:655,y:500},{x:750,y:600},{x:840,y:700},{x:935,y:805},{x:1050,y:880},{x:1140,y:985}];
 const populations=[...allHoppers.slice(0,config.grasshoppers).map((pos,i)=>({id:`grasshopper-${i+1}`,role:'grasshopper',...pos})),...caterpillars.slice(0,config.caterpillars).map((pos,i)=>({id:`caterpillar-${i+1}`,role:'caterpillar',...pos}))];
 const baseCover=[{id:'cover-west',x:430,y:670,r:64},{id:'cover-midwest',x:605,y:775,r:62},{id:'cover-middle',x:800,y:910,r:70},{id:'cover-east',x:1020,y:1090,r:66},{id:'cover-north',x:640,y:520,r:65}];
 const predatorRole=role==='frog'?'snake':'frog',s={id:`${predatorRole}-1`,role:predatorRole,developmentArt:false,x:940,y:1050,r:predatorRole==='snake'?SNAKE.headRadius:34,home:{x:940,y:1050},state:'patrol',stateTime:0,facing:-1,z:0,face:{x:-1,y:0},locked:{x:-1,y:0},lastSeen:null,warning:null,warningVisibleTime:0,attackProgress:0};
 const w={width:SETTINGS.worldWidth,height:SETTINGS.worldHeight,seed,stage:config.id,segment:config.segment,role,config,quota:config.quota,timeLimit:config.timeLimit,fastTime:config.fastTime,destination:{x:config.id===1?970:role==='frog'?1165:1195,y:config.id===1?870:role==='frog'?1070:1090,r:52,label:config.destinationLabel},settings:options,assisted:isAssisted(options)||Boolean(checkpoint?.first?.assisted),timed:!options.untimed,time:0,paused:false,status:'playing',reason:'',events:[],route:[{time:0,x:p.x,y:p.y}],navigation:{...NAV,worldMeadow:worldPoly(NAV.meadow),worldWater:worldPoly(NAV.water)},rocks:NAV.rocks.map(r=>({...r,polygon:worldPoly(r.polygon)})),cover:baseCover.filter(c=>config.id!==4||!['cover-midwest','cover-middle'].includes(c.id)),removedCover:config.id===4?baseCover.filter(c=>['cover-midwest','cover-middle'].includes(c.id)):[],player:p,spawn,prey:populations.map((q,i)=>({...q,r:q.role==='caterpillar'?16:17,alive:true,captured:false,home:{x:q.x,y:q.y},roamRadius:config.id===1&&i<3?30:55,phase:rng()*6.28,cooldown:2+rng(),state:'feeding'})),grass:[],predator:s,rng,escapeRemaining:1,escapeUsed:false,immuneUntil:0,checkpoint:checkpoint?structuredClone(checkpoint):null,segmentRetry:Boolean(segmentRetry),continued:Boolean(checkpoint?.first?.continued),scoreEligible:!isAssisted(options)&&!segmentRetry&&(config.segment===0||Boolean(checkpoint?.first?.eligible)),aiConsumed:0,aiConsumptionLimit:role==='frog'?0:config.id===6?1:2,visibleBounds:null,result:null,goalReached:false,inputLatch:{jump:false},pendingEat:null};
 if(config.grassBites){const cap=config.id===6?3:4;w.grass=[{x:440,y:680},{x:750,y:950},{x:1100,y:1130}].map((g,i)=>({id:`grass-${i+1}`,...g,r:58,capacity:cap,bites:cap,remaining:cap,consumed:0}));}
 if(predatorRole==='snake')seedMeadowSnake(s);
 addEvent(w,'stage-start',{role,stage:w.stage,segment:w.segment,quota:w.quota,timeLimit:w.timeLimit,category:'model-rule'});return w;
}
export function addEvent(w,type,details={}){const point=details.position,observed=details.observed??(details.actor===w.player.id||Boolean(point&&pointVisible(w,point)));w.events.push({time:Number(w.time.toFixed(3)),stage:w.stage,segment:w.segment,type,observed,category:details.category??'game-action',...details});}
function notice(w,text){w.player.feedback={text,until:w.time+2.2};}
export function setVisibility(w,bounds){w.visibleBounds=bounds?{...bounds,exclusions:[...(bounds.exclusions??[])]}:null;}
export function pointVisible(w,p,r=0){const b=w.visibleBounds;if(!b||p.x-r<b.left||p.x+r>b.right||p.y-r<b.top||p.y+r>b.bottom)return false;return !(b.exclusions??[]).some(e=>p.x+r>e.left&&p.x-r<e.right&&p.y+r>e.top&&p.y-r<e.bottom);}
export function predatorVisible(w,s=w.predator){if(!s)return false;const head=s.role==='frog'?tongueGeometry(s,0).mouth:{x:s.x,y:s.y-SNAKE.headGroundOffset/ART.groundY};return pointVisible(w,s,s.r)&&pointVisible(w,head,s.role==='frog'?40:34);}
export function warningVisible(w,warning){if(!warning||!pointVisible(w,warning.start,warning.r)||!pointVisible(w,warning.end,warning.r))return false;return !(w.visibleBounds.exclusions??[]).some(e=>polygonLine(warning.start,warning.end,[[e.left-warning.r,e.top-warning.r],[e.right+warning.r,e.top-warning.r],[e.right+warning.r,e.bottom+warning.r],[e.left-warning.r,e.bottom+warning.r]]));}
export function getJumpReadiness(w){const p=w.player,airborne=p.state==='jumping',eating=p.state==='eating',remaining=Math.max(0,p.jumpRecovery??0,p.landingLock??0,eating?EAT_DURATION-p.stateTime:0),ready=!w.paused&&w.status==='playing'&&!airborne&&!eating&&remaining<=1e-7;return{ready,remaining,airborne,label:w.paused?'일시정지':w.status!=='playing'?'판 종료':airborne?'착지 후 준비':eating?'먹기 후 준비':ready?'준비':`준비까지 ${Math.ceil(remaining)}초`};}
function clearStride(p){p.stride=null;p.pose=null;p.z=0;if(p.state==='moving')p.state='idle';p.pendingAction=null;}
export function clearPendingInput(w){w.pendingEat=null;w.player.pendingAction=null;w.inputLatch={jump:false};}
export function pauseWorld(w,paused=true){clearPendingInput(w);if(paused&&w.role==='grasshopper')cancelGrazing(w);w.paused=Boolean(paused);if(w.predator?.state==='windup'){w.predator.warningVisibleTime=0;w.predator.stateTime=0;}return w;}
export function requestJump(w,direction={x:0,y:0},kind='big'){
 const p=w.player;if(w.paused||w.status!=='playing')return false;
 if(!getJumpReadiness(w).ready||p.state==='eating'){notice(w,getJumpReadiness(w).label);return false;}
 kind=kind==='short'?'short':'big';let dir=normalize(direction);if(length(dir)<.01)dir={x:facing(p),y:0};const rig=RIGS[kind],travel=rig.travel*ART.scale,end={x:p.x+dir.x*travel,y:p.y+dir.y*travel};
 if(!clearGroundPath(w,p,end,p.r)){notice(w,'앞이 막혔어요 · 방향을 바꿔 보세요');addEvent(w,'jump-blocked',{actor:p.id,kind});return false;}
 cancelGrazing(w);clearStride(p);p.facing=Math.abs(dir.x)>.1?Math.sign(dir.x):facing(p);p.face={x:p.facing,y:0};p.jumpDirection=dir;p.jumpKind=kind;p.jumpDuration=rig.duration;p.jumpOrigin={x:p.x,y:p.y};p.state='jumping';p.stateTime=0;p.pose=hopPose(kind,0);p.jumpRecovery=SETTINGS.jumpRecovery;p.jumpCooldown=SETTINGS.jumpRecovery;p.landingLock=0;w.pendingEat=null;addEvent(w,'jump',{actor:p.id,kind,duration:rig.duration,position:{x:p.x,y:p.y}});return true;
}
export function selectFoodTarget(w){const p=w.player;if(w.role==='grasshopper')return w.grass.filter(g=>g.remaining>0&&distance(p,g)<=g.r+p.r*.35).sort((a,b)=>distance(p,a)-distance(p,b)||a.id.localeCompare(b.id))[0]??null;const sign=facing(p),cos=Math.cos(50*Math.PI/180);return w.prey.filter(q=>{if(!q.alive||q.captured||!['grasshopper','caterpillar'].includes(q.role))return false;const dx=(q.x-p.x)*sign,dy=(q.y-p.y)*ART.groundY,d=Math.hypot(dx,dy);return dx>72&&d<=SETTINGS.tongueReach+(q.r??0)*.25&&dx/(d||1)>=cos&&!blockedLine(w,p,q);}).sort((a,b)=>Math.hypot(a.x-p.x,(a.y-p.y)*ART.groundY)-Math.hypot(b.x-p.x,(b.y-p.y)*ART.groundY)||a.id.localeCompare(b.id))[0]??null;}
export function getEatTarget(w){return selectFoodTarget(w);}
function aimTransform(p,q){const full=tongueGeometry(p,GAME_EAT.contact),sx=(q.x-full.mouth.x)/(ART.scale*facing(p)),sy=((q.y-full.mouth.y)*ART.groundY-(q.z??0))/ART.scale,ax=(full.tip.x-full.mouth.x)/(ART.scale*facing(p)),ay=(full.tip.y-full.mouth.y)*ART.groundY/ART.scale,angle=Math.atan2(sy,sx)-Math.atan2(ay,ax),scale=Math.hypot(sx,sy)/Math.hypot(ax,ay),u={x:ax/Math.hypot(ax,ay),y:ay/Math.hypot(ax,ay)},c=Math.cos(angle),s=Math.sin(angle),xx=1+(scale-1)*u.x*u.x,xy=(scale-1)*u.x*u.y,yy=1+(scale-1)*u.y*u.y,a=c*xx-s*xy,b=s*xx+c*xy,cc=c*xy-s*yy,d=s*xy+c*yy,m=MOUTH.center;return{angle,scale,matrix:[a,b,cc,d,m[0]-a*m[0]-cc*m[1],m[1]-b*m[0]-d*m[1]]};}
export function playerTongueGeometry(p,time=p.stateTime){const g=tongueGeometry(p,time),m=p.tongue?.aim?.matrix;if(!m)return g;const source=[ART.pivot.x+(g.tip.x-p.x)/(ART.scale*facing(p)),ART.pivot.y+(g.tip.y-p.y)*ART.groundY/ART.scale],tip=[m[0]*source[0]+m[2]*source[1]+m[4],m[1]*source[0]+m[3]*source[1]+m[5]];return{...g,tip:{x:p.x+(tip[0]-ART.pivot.x)*ART.scale*facing(p),y:p.y+(tip[1]-ART.pivot.y)*ART.scale/ART.groundY}};}
export function requestEat(w){const p=w.player;if(w.paused||w.status!=='playing'||p.eatCooldown>0)return false;if(p.state==='jumping'){if(p.jumpDuration-p.stateTime<=.15+1e-7){w.pendingEat={expires:w.time+.15};return true;}return false;}if(p.state==='eating')return false;if(w.role==='grasshopper'){const patch=selectFoodTarget(w);if(!patch){notice(w,'풀 군락 가까이에서 먹기를 누르고 있어요');return false;}clearStride(p);p.state='grazing';p.grazeTarget=patch.id;return true;}
 const q=selectFoodTarget(w),base=tongueGeometry(p,GAME_EAT.contact);if(blockedLine(w,p,base.mouth)||blockedLine(w,base.mouth,q??base.tip)){notice(w,'바위가 혀를 막아요');addEvent(w,'eat-blocked',{actor:p.id});return false;}clearStride(p);p.eatCooldown=SETTINGS.eatCooldown;p.state='eating';p.stateTime=0;p.tongue={caught:null,committed:false,previousTip:null,target:q?.id??null,aim:q?aimTransform(p,q):null};addEvent(w,'eat-start',{actor:p.id,target:q?.id??null});return true;}
export function playerHidden(w){return w.cover.some(c=>distance(w.player,c)<c.r*.8);}
function cancelGrazing(w){const p=w.player;p.grazeProgress=0;p.grazeTarget=null;if(p.state==='grazing'){p.state='idle';p.stateTime=0;}}
function cancelAction(w){const p=w.player;if(p.tongue?.caught&&!p.tongue.committed){const q=w.prey.find(q=>q.id===p.tongue.caught);if(q){q.captured=false;q.state='feeding';}addEvent(w,'catch-cancelled',{actor:p.id,target:q?.id});}p.tongue=null;clearStride(p);p.state='idle';p.stateTime=0;p.z=0;p.pose=null;cancelGrazing(w);clearPendingInput(w);}
function foodCommitted(w,food,target,position){const p=w.player;p.eaten++;p.jumpRecovery=0;addEvent(w,'ate',{actor:p.id,eater:w.role,food,target,position,observed:true,source:'textbook-49',category:'observed-game-event'});if(!w.goalReached&&p.eaten>=w.quota){w.goalReached=true;addEvent(w,'quota-reached',{actor:p.id,count:p.eaten,quota:w.quota});notice(w,'먹기 목표 완료 · 도착 지점으로!');}else notice(w,p.eaten>w.quota?`선택 먹이 +${Math.min(2,p.eaten-w.quota)} / 2`:`${p.eaten} / ${w.quota} · 먹으면 도약 회복이 빨라져요`);}
export function calculateScore(w){const succeeded=w.status==='success'||w.status==='transition',segmentScore=scoreSegment({success:succeeded,eaten:w.player.eaten,quota:w.quota,elapsed:w.time,timeLimit:w.timeLimit,fastTime:w.fastTime,escapeUsed:w.escapeUsed,eligible:w.scoreEligible});if(w.stage===6&&w.segment===1&&w.checkpoint?.first){const first=w.checkpoint.first.score,eligible=segmentScore.eligible&&Boolean(first?.eligible)&&!w.segmentRetry;const total=succeeded?Math.floor(((first?.total??0)+segmentScore.total)/2):0;return{...segmentScore,eligible,completed:succeeded,total,stars:eligible?(total>=900?3:total>=800?2:1):0,segments:[first,segmentScore],reason:eligible?'두 구간 연속 기본 도전 기록':segmentScore.reason};}return segmentScore;}
function endRound(w,status,reason){if(w.status!=='playing')return;recordRoute(w,true);cancelAction(w);w.status=status;w.reason=reason;addEvent(w,'round-end',{status,reason});w.result=calculateScore(w);if(status==='transition')w.checkpoint={stage:6,seed:w.seed,settings:{...w.settings},first:{score:{...w.result},elapsed:w.time,eaten:w.player.eaten,escapeUsed:w.escapeUsed,eligible:w.result.eligible,assisted:w.assisted,continued:w.continued,route:structuredClone(w.route),events:structuredClone(w.events)}};}
function reachedDestination(w){return w.player.eaten>=w.quota&&distance(w.player,w.destination)<=w.destination.r&&w.player.state!=='jumping'&&(!w.timed||w.time<=w.timeLimit+1e-7);}
function checkSuccess(w){if(!reachedDestination(w))return false;endRound(w,w.stage===6&&w.segment===0?'transition':'success','먹기 목표를 채우고 도착했어요');return true;}
export function advanceSegment(w){if(w.stage!==6||w.segment!==0||w.status!=='transition'||!w.checkpoint)return w;return createWorld({stage:6,segment:1,seed:w.seed,settings:w.settings,checkpoint:w.checkpoint});}
export function retryWorld(w,{full=false}={}){const segment=w.stage===6&&w.segment===1&&!full?1:0;return createWorld({stage:w.stage,segment,seed:w.seed,settings:w.settings,checkpoint:segment?w.checkpoint:null,segmentRetry:segment===1});}
export function continueWorld(w){if(!['failed','playing'].includes(w.status))return w;cancelAction(w);w.status='playing';w.reason='';w.result=null;w.timed=false;w.continued=true;w.scoreEligible=false;w.settings={...w.settings,untimed:true};w.escapeRemaining=0;w.immuneUntil=w.time+3;moveToSafety(w);addEvent(w,'continue',{actor:w.player.id,category:'model-rule'});return w;}
export function applySettings(w,settings){w.settings=normalizeSettings(settings);if(isAssisted(w.settings)){w.assisted=true;w.scoreEligible=false;}w.timed=!w.settings.untimed&&!w.continued;return w;}
function projected(p){return{x:p.x,y:p.y*ART.groundY-(p.z??0)};}
function touchPrey(a,b,q){const c=projected(q),pa=projected(a),pb=projected(b);return segmentHitsCircle({x:(pa.x-c.x)/(ART.preyRadiusX+1.4),y:(pa.y-c.y)/(ART.preyRadiusY+1.4)},{x:(pb.x-c.x)/(ART.preyRadiusX+1.4),y:(pb.y-c.y)/(ART.preyRadiusY+1.4)},{x:0,y:0,r:1});}
function stepPlayer(w,input,dt){const p=w.player;p.eatCooldown=Math.max(0,p.eatCooldown-dt);if(p.state!=='jumping'){p.jumpRecovery=Math.max(0,p.jumpRecovery-dt);p.landingLock=Math.max(0,p.landingLock-dt);}p.jumpCooldown=Math.max(p.jumpRecovery,p.landingLock);p.stateTime+=dt;if(p.feedback&&w.time>p.feedback.until)p.feedback=null;
 if(p.state==='jumping'){const rig=RIGS[p.jumpKind],pose=hopPose(p.jumpKind,p.stateTime);p.pose=pose;p.x=p.jumpOrigin.x+p.jumpDirection.x*pose.root.travel*ART.scale;p.y=p.jumpOrigin.y+p.jumpDirection.y*pose.root.travel*ART.scale;p.z=Math.max(0,pose.root.height*ART.scale);if(p.stateTime+1e-9>=rig.duration){p.x=p.jumpOrigin.x+p.jumpDirection.x*rig.travel*ART.scale;p.y=p.jumpOrigin.y+p.jumpDirection.y*rig.travel*ART.scale;p.z=0;p.state='idle';p.stateTime=0;p.pose=null;p.landingLock=SETTINGS.landingLock;addEvent(w,'land',{actor:p.id,kind:p.jumpKind,position:{x:p.x,y:p.y}});const queued=w.pendingEat;w.pendingEat=null;if(queued&&queued.expires>=w.time-1e-7&&!input.cancelEat)requestEat(w);}return;}
 if(p.state==='eating'){const action=p.tongue,g=playerTongueGeometry(p);if(action&&!action.caught&&g.visible&&p.stateTime<=GAME_EAT.hold+1e-9){const prior=action.previousTip??g.mouth;const hits=w.prey.filter(q=>q.alive&&!q.captured&&['grasshopper','caterpillar'].includes(q.role)&&touchPrey(prior,g.tip,q)&&!blockedLine(w,g.mouth,q)).sort((a,b)=>distance(g.mouth,a)-distance(g.mouth,b)||a.id.localeCompare(b.id));const q=hits[0];if(q){action.caught=q.id;action.capture={time:p.stateTime,reach:g.pose.reach,offset:[0,0]};action.preySnapshot=structuredClone(q);q.captured=true;q.state='carried';addEvent(w,'tongue-contact',{actor:p.id,target:q.id,food:q.role,position:{x:q.x,y:q.y},tip:{...g.tip},observed:true});}}
  if(action){action.previousTip=g.visible?g.tip:null;if(action.caught&&!action.committed&&p.stateTime>=GAME_EAT.commit-1e-9){const q=w.prey.find(q=>q.id===action.caught);if(q?.alive&&q.captured){q.alive=false;q.captured=false;action.committed=true;foodCommitted(w,q.role,q.id,{x:q.x,y:q.y});}}}
  if(p.stateTime+1e-9>=EAT_DURATION){p.state='idle';p.stateTime=0;p.tongue=null;}return;
 }
 const magnitude=length(input.move??{x:0,y:0});if(w.role==='grasshopper'&&(input.eatHeld||input.eat)&&magnitude<=SETTINGS.inputDeadzone){const patch=selectFoodTarget(w);if(patch){clearStride(p);p.state='grazing';p.grazeTarget=patch.id;p.grazeProgress+=dt;if(p.grazeProgress+1e-9>=SETTINGS.grassBiteSeconds){p.grazeProgress-=SETTINGS.grassBiteSeconds;patch.remaining--;patch.consumed++;foodCommitted(w,'grass',`${patch.id}-bite-${patch.consumed}`,{x:patch.x,y:patch.y});if(!patch.remaining)cancelGrazing(w);}return;}}
 if(p.state==='grazing')cancelGrazing(w);
 if(p.stride){const stride=p.stride;if(stride.time/STRIDE.duration<STRIDE.moveStart&&magnitude<=SETTINGS.inputDeadzone&&!stride.precision){stride.delta.x*=.28;stride.delta.y*=.28;stride.precision=true;}stride.time+=dt;const progress=strideProgress(stride.time);p.x=stride.origin.x+stride.delta.x*progress;p.y=stride.origin.y+stride.delta.y*progress;p.pose=w.role==='frog'?stridePose(stride.time):null;p.z=w.role==='frog'?Math.max(0,p.pose.root.height*ART.scale):Math.sin(Math.PI*progress)*10;p.state='moving';
  if(stride.time+1e-9>=STRIDE.duration){p.x=stride.origin.x+stride.delta.x;p.y=stride.origin.y+stride.delta.y;p.stride=null;p.pose=null;p.z=0;p.state='idle';p.stateTime=0;}return;
 }
 const dir=magnitude>SETTINGS.inputDeadzone?normalize(input.move):{x:0,y:0};if(length(dir)){
  if(Math.abs(dir.x)>.1)p.facing=Math.sign(dir.x);p.face={x:facing(p),y:0};let step=STRIDE.distance*Math.max(.25,Math.min(1,magnitude));const destination=n=>({x:p.x+dir.x*n,y:p.y+dir.y*n});if(!clearGroundPath(w,p,destination(step),p.r)){let low=0,high=step;for(let i=0;i<12;i++){const mid=(low+high)/2;if(clearGroundPath(w,p,destination(mid),p.r))low=mid;else high=mid;}step=low;}if(step>1){p.stride={time:dt,origin:{x:p.x,y:p.y},delta:{x:dir.x*step,y:dir.y*step},direction:{...dir}};p.pose=w.role==='frog'?stridePose(dt):null;p.state='moving';p.z=p.pose?Math.max(0,p.pose.root.height*ART.scale):0;}else{p.state='idle';p.pose=null;p.z=0;}
 }else{p.state='idle';p.pose=null;p.z=0;}
}
function stepPrey(w,dt){const hoppers=w.prey.filter(q=>q.role==='grasshopper');stepPreyMotion({...w,prey:hoppers},dt,{clearGroundPath:(world,a,b,r)=>clearGroundPath(world,a,b,r)&&(!a.home||distance(b,a.home)<=a.roamRadius),blockedLine,onFeeding:q=>{if(pointVisible(w,q,q.r))addEvent(w,'feeding-observed',{actor:q.id,eater:'grasshopper',food:'grass',position:{x:q.x,y:q.y},observed:true,source:'textbook-49',category:'observed-game-event',consumption:0});}});for(const q of w.prey){if(q.role!=='caterpillar'||!q.alive||q.captured)continue;q.phase+=dt;const dx=Math.cos(q.phase*.3)*7*dt,dy=Math.sin(q.phase*.22)*4*dt,next={x:q.x+dx,y:q.y+dy};if((!q.home||distance(next,q.home)<28)&&clearGroundPath(w,q,next,q.r)){q.x=next.x;q.y=next.y;q.facing=dx>=0?1:-1;}q.z=0;}}
/** Snake steering has a distance-bound curvature budget, never an in-place pivot. */
export function steerSnake(s,target,dt,speed=48){
 const current=Math.atan2(s.face.y,s.face.x),wanted=Math.atan2(target.y,target.x),delta=Math.atan2(Math.sin(wanted-current),Math.cos(wanted-current));
 const angle=current+clamp(delta,-speed/SNAKE.turnRadius*dt,speed/SNAKE.turnRadius*dt);
 return{direction:{x:Math.cos(angle),y:Math.sin(angle)},alignment:Math.cos(delta)};
}
export function moveSnake(w,s,target,speed,dt){
 const current=Math.atan2(s.face.y,s.face.x),wanted=Math.atan2(target.y,target.x),delta=Math.atan2(Math.sin(wanted-current),Math.cos(wanted-current));
 let turn=clamp(delta/(speed*dt||1),-1/SNAKE.turnRadius,1/SNAKE.turnRadius);
 if(s.state!=='attack'){
  // Test whole forward arcs before the nose reaches a wall. Axis sliding or
  // turning a stationary head would kink the neck and invalidate its trail.
  const max=1/SNAKE.turnRadius,turns=[turn,-max,0,max],look=SNAKE.turnRadius*1.45;
  const lookRadius=canStand(w,s,SNAKE.navigationRadius)?SNAKE.navigationRadius:s.r+3;
  let best=-Infinity;
  for(const curvature of turns){let previous={x:s.x,y:s.y},safe=0;
   for(let d=18;d<=look;d+=18){const angle=current+curvature*d,p=Math.abs(curvature)<1e-8?{x:s.x+Math.cos(current)*d,y:s.y+Math.sin(current)*d}:{x:s.x+(Math.sin(angle)-Math.sin(current))/curvature,y:s.y-(Math.cos(angle)-Math.cos(current))/curvature};
    if(!clearGroundPath(w,previous,p,lookRadius))break;safe=d;previous=p;
   }
   const end=current+curvature*Math.min(look,120),score=safe*4+Math.cos(wanted-end)*45-Math.abs(curvature-turn)*.01;
   if(score>best){best=score;turn=curvature;}
  }
 }
 const angle=current+turn*speed*dt,direction={x:Math.cos(angle),y:Math.sin(angle)},dx=direction.x*speed*dt,dy=direction.y*speed*dt;
 if(clearGroundPath(w,s,{x:s.x+dx,y:s.y+dy},s.r)){s.face=direction;s.x+=dx;s.y+=dy;}
 return Math.cos(delta);
}
function bodySamples(s){if(s?.role!=='snake'||!s.skin)return[];const trail=s.skin.trail,samples=[];let previous=null;for(let i=trail.length-1;i>=0;i--){const q=trail[i],behind=s.skin.distance-q.s;if(behind<60||behind>SNAKE.bodyLength*.88)continue;if(!previous||distance(q,previous)>35){samples.push(q);previous=q;}}return samples;}
function safePosition(w,p){const s=w.predator;if(!canStand(w,p,w.player.r))return false;if(s&&!s.disabled&&(distance(p,s)<w.player.r+s.r+70||bodySamples(s).some(q=>distance(p,q)<w.player.r+25)))return false;if(s?.warning&&segmentHitsCircle(s.warning.start,s.warning.end,p,w.player.r+s.warning.r+15))return false;return true;}
export function findSafePosition(w){const p=w.player,s=w.predator,away=s?Math.atan2(p.y-s.y,p.x-s.x):0;for(const radius of [80,110,145,190,240,300,380,480])for(const offset of [0,.4,-.4,.8,-.8,1.25,-1.25,1.8,-1.8,Math.PI]){const pos={x:p.x+Math.cos(away+offset)*radius,y:p.y+Math.sin(away+offset)*radius};if(safePosition(w,pos))return pos;}if(safePosition(w,w.spawn))return{...w.spawn};for(let y=400;y<w.height-80;y+=45)for(let x=280;x<w.width-80;x+=45){const pos={x,y};if(safePosition(w,pos))return pos;}return null;}
function moveToSafety(w){const pos=findSafePosition(w);if(!pos){w.predator.state='recover';w.predator.stateTime=-3;w.predator.warning=null;return false;}Object.assign(w.player,pos);recordRoute(w,true,'escape');return true;}
export function capturePlayer(w,predator=w.predator){const p=w.player;if(w.status!=='playing'||w.time<w.immuneUntil)return false;if(p.state==='jumping'&&p.z>=SETTINGS.attackHeight)return false;addEvent(w,'capture',{actor:predator.id,target:p.id,eater:predator.role,food:w.role,position:{x:p.x,y:p.y},observed:true,category:'observed-game-event',consumed:false});if(w.escapeRemaining>0||w.continued){cancelAction(w);if(!w.continued){w.escapeRemaining=0;w.escapeUsed=true;}w.immuneUntil=w.time+3;moveToSafety(w);predator.state='recover';predator.stateTime=0;predator.warning=null;predator.warningVisibleTime=0;notice(w,w.continued?'안전한 곳에서 이어 체험해요':'탈출 기회를 썼어요 · 3초간 안전');addEvent(w,'escape-used',{actor:p.id,remaining:0,immunity:3,position:{x:p.x,y:p.y},category:'model-rule'});return true;}endRound(w,'failed',p.state==='jumping'?'이륙하거나 착지할 때 공격선에 닿았어요':'예고된 공격선에 다시 잡혔어요');return true;}
function bodyPush(w){const p=w.player,s=w.predator;if(!s||s.disabled||s.role!=='snake'||(w.stage===1&&p.eaten<2)||(p.state==='jumping'&&p.z>=SETTINGS.attackHeight))return;const sample=bodySamples(s).find(q=>distance(p,q)<p.r+16);if(!sample)return;const delta=normalize({x:p.x-sample.x,y:p.y-sample.y}),n=length(delta)?delta:{x:0,y:1},need=p.r+18-distance(p,sample),target={x:p.x+n.x*need,y:p.y+n.y*need};if(clearGroundPath(w,p,target,p.r)){clearStride(p);p.x=target.x;p.y=target.y;}else{const tangent={x:-n.y,y:n.x};for(const sign of [1,-1]){const slide={x:p.x+tangent.x*16*sign,y:p.y+tangent.y*16*sign};if(clearGroundPath(w,p,slide,p.r)){clearStride(p);p.x=slide.x;p.y=slide.y;break;}}}}
function beginWarning(w,s){const p=w.player;if(s.role==='frog'){s.facing=p.x>=s.x?1:-1;s.face={x:s.facing,y:0};}const start=s.role==='frog'?tongueGeometry(s,0).mouth:{x:s.x,y:s.y},direction=s.role==='snake'?{...s.face}:normalize({x:p.x-start.x,y:p.y-start.y}),range=s.role==='snake'?128:165,r=s.role==='snake'?s.r*.8:13,warning={start:{...start},end:{x:start.x+direction.x*range,y:start.y+direction.y*range},r,radius:r};if(!warningVisible(w,warning)||!predatorVisible(w,s))return false;s.state='windup';s.stateTime=0;s.warningVisibleTime=0;s.locked=direction;s.warning=warning;s.attackOrigin={x:s.x,y:s.y};s.attackProgress=0;addEvent(w,'predator-warning',{actor:s.id,duration:w.settings.longWarning?1.8:1.2,position:{x:s.x,y:s.y},observed:true,consumed:false});return true;}
function cancelWarning(w,s){if(s.warningVisibleTime>0)addEvent(w,'warning-reset',{actor:s.id,position:{x:s.x,y:s.y},observed:false});s.warningVisibleTime=0;s.stateTime=0;}
function stepPredator(w,dt){const s=w.predator,p=w.player;if(!s||s.disabled)return;s.stateTime+=dt;const speed=w.settings.slowPredators ? .8 : 1,visible=distance(s,p)<360&&distance(p,s.home)<390&&!playerHidden(w)&&!blockedLine(w,s,p);if(visible)s.lastSeen={x:p.x,y:p.y};
 if(s.state==='windup'){if(!warningVisible(w,s.warning)||!predatorVisible(w,s)){cancelWarning(w,s);s.state='search';s.warning=null;return;}s.warningVisibleTime+=dt;const duration=w.settings.longWarning?1.8:SETTINGS.windupSeconds;if(s.warningVisibleTime+1e-9>=duration){s.state='attack';s.stateTime=0;s.attackProgress=0;addEvent(w,'predator-attack',{actor:s.id,direction:{...s.locked},position:{x:s.x,y:s.y},observed:true,warningDuration:s.warningVisibleTime,consumed:false});}return;}
 if(s.state==='attack'){if(!warningVisible(w,s.warning)||!predatorVisible(w,s)){s.state='recover';s.stateTime=0;s.warning=null;return;}s.attackProgress=clamp(s.stateTime/(SETTINGS.attackSeconds/speed),0,1);let hit=false;if(s.role==='snake'){const previous={x:s.x,y:s.y},end={x:s.attackOrigin.x+(s.warning.end.x-s.warning.start.x)*s.attackProgress,y:s.attackOrigin.y+(s.warning.end.y-s.warning.start.y)*s.attackProgress};if(clearGroundPath(w,s,end,s.r)){s.x=end.x;s.y=end.y;}hit=segmentHitsCircle(previous,s,p,p.r+s.warning.r);}else{const end={x:s.warning.start.x+(s.warning.end.x-s.warning.start.x)*s.attackProgress,y:s.warning.start.y+(s.warning.end.y-s.warning.start.y)*s.attackProgress};hit=segmentHitsCircle(s.warning.start,end,p,p.r+s.warning.r);}
 if(hit&&capturePlayer(w,s))return;if(s.attackProgress>=1){s.state='recover';s.stateTime=0;s.warning=null;addEvent(w,'predator-missed',{actor:s.id,position:{x:s.x,y:s.y},observed:true});}return;}
 if(s.state==='recover'){if(s.stateTime>=SETTINGS.predatorRecovery){s.state='search';s.stateTime=0;}return;}
 if(w.stage===1&&p.eaten<2){s.state='patrol';return;}
 if(visible){const dir=normalize({x:p.x-s.x,y:p.y-s.y}),alignment=s.face.x*dir.x+s.face.y*dir.y;if(distance(s,p)<(s.role==='snake'?175:230)&&(s.role==='frog'||alignment>.94)&&beginWarning(w,s))return;s.state='approach';if(s.role==='snake')moveSnake(w,s,dir,48*speed,dt);else{if(Math.abs(dir.x)>.1)s.facing=Math.sign(dir.x);s.face={x:s.facing,y:0};moveBody(w,s,dir.x*34*speed*dt,dir.y*34*speed*dt);}return;}
 if(s.lastSeen&&s.state!=='patrol'){if(s.state!=='search'){s.state='search';s.stateTime=0;}if(s.stateTime>2.5||distance(s,s.home)>340){s.lastSeen=null;s.state='patrol';s.stateTime=0;}else if(s.role==='snake')moveSnake(w,s,normalize({x:s.lastSeen.x-s.x,y:s.lastSeen.y-s.y}),36*speed,dt);return;}
 s.state='patrol';const target={x:s.home.x+Math.cos(w.time*.35)*65,y:s.home.y+Math.sin(w.time*.35)*45};if(s.role==='snake')moveSnake(w,s,normalize({x:target.x-s.x,y:target.y-s.y}),32*speed,dt);else{const dir=normalize({x:target.x-s.x,y:target.y-s.y});if(Math.abs(dir.x)>.1)s.facing=Math.sign(dir.x);moveBody(w,s,dir.x*20*speed*dt,dir.y*20*speed*dt);}
}
export function foodBudget(w){const available=w.role==='frog'?w.prey.filter(q=>q.alive&&canStand(w,q,q.r)).length:w.grass.reduce((n,g)=>n+g.remaining,0),required=Math.max(0,w.quota-w.player.eaten)+Math.max(0,2-Math.max(0,w.player.eaten-w.quota));return{available,required,valid:available>=required,aiConsumed:w.aiConsumed,aiLimit:w.aiConsumptionLimit};}
function recordRoute(w,force=false,reason=null){const last=w.route.at(-1),p=w.player;if(force||distance(last,p)>=24||w.time-last.time>=.5&&distance(last,p)>.5)w.route.push({time:Number(w.time.toFixed(3)),x:p.x,y:p.y,...(reason?{break:true,reason}:{})});}
export function stepWorld(w,input={},dt=SETTINGS.fixedStep){if(!Number.isFinite(dt)||dt<0)throw new Error('Invalid simulation delta');if(w.paused){if(w.pendingEat||w.player.pendingAction)clearPendingInput(w);return;}if(w.status!=='playing'||dt===0)return;if(isAssisted(w.settings)||!w.timed){w.scoreEligible=false;if(!w.continued)w.assisted=true;}dt=Math.min(dt,SETTINGS.maxFrameDelta);
 if(w.timed&&w.time>=w.timeLimit-1e-9){w.time=w.timeLimit;endRound(w,'failed','시간 내에 먹기 목표와 도착을 모두 마치지 못했어요');return;}if(checkSuccess(w))return;
 const move=input.move??{x:0,y:0};if(input.cancelEat){w.pendingEat=null;if(w.role==='grasshopper')cancelGrazing(w);}if(w.pendingEat&&w.pendingEat.expires<w.time)w.pendingEat=null;
 if((!w.player.stride||input.eat||input.jump)&&!['jumping','eating'].includes(w.player.state)&&Math.abs(move.x)>SETTINGS.inputDeadzone){w.player.facing=Math.sign(move.x);w.player.face={x:w.player.facing,y:0};}
 const jumpEdge=Boolean(input.jump)&&!w.inputLatch.jump;w.inputLatch.jump=Boolean(input.jump);if(jumpEdge)requestJump(w,move,'big');if(input.eat||(input.eatHeld&&w.role==='frog'&&w.settings.eatHold))requestEat(w);
 const remaining=w.timed?w.timeLimit-w.time:dt;dt=Math.min(dt,remaining);w.time+=dt;stepPlayer(w,{...input,move},dt);if(checkSuccess(w))return;bodyPush(w);stepPrey(w,dt);stepPredator(w,dt);recordRoute(w);if(w.predator?.role==='snake'&&!w.predator.disabled)updateSnakeTrail(w.predator,dt);if(w.status==='playing'&&w.timed&&w.time>=w.timeLimit-1e-9){w.time=w.timeLimit;endRound(w,'failed','시간 내에 먹기 목표와 도착을 모두 마치지 못했어요');}}
export function cameraTarget(p,view,w){const x=p.x+facing(p)*40,y=p.y-Math.min(105,view.height*.62*.30)/.62;return{x:w.width<=view.width?w.width/2:clamp(x,view.width/2,w.width-view.width/2),y:w.height<=view.height?w.height/2:clamp(y,view.height/2,w.height-view.height/2)};}
export function smoothCamera(camera,target,dt,deadzone=20){const t=1-Math.exp(-7*dt);for(const axis of ['x','y']){const delta=target[axis]-camera[axis];if(Math.abs(delta)>deadzone)camera[axis]+=(delta-Math.sign(delta)*deadzone)*t;}return camera;}
