import {SETTINGS,createWorld,stepWorld,getJumpReadiness,retryWorld,continueWorld,advanceSegment,pauseWorld,calculateScore,applySettings,clearPendingInput} from './core.js';
import {STAGES,getStage,normalizeSettings,createProgress,recordCompletion,campaignComplete} from './campaign.js';
import {createRenderer} from './render.js';
import {createInput,GAME_KEYS} from './input.js';
import {createLifecycle} from './lifecycle.js';
import {loadAssets} from './assets.js';
import {renderLearningPanel} from './learning.js';
import {createStorage,runRecord,upsertRun} from './storage.js';
import {createAudio} from './audio.js';
import {drawRouteRecap} from './recap.js';

const $=id=>document.getElementById(id),canvas=$('world'),dialog=$('dialog');
let storageError=false,local=null;try{local=globalThis.localStorage;}catch{storageError=true;}
const save=createStorage(local,()=>{storageError=true;});
let settings={...normalizeSettings(save.read('settings',{})),sound:true,volume:.45,showTouch:false,mouse:false,...save.read('settings',{})};
let progress=save.read('progress',createProgress()),activities=save.read('activities',{}),runs=save.read('runs',[]),checkpoint=save.read('checkpoint',null);
if(!progress||typeof progress!=='object'||!progress.completed)progress=createProgress();if(!Array.isArray(runs))runs=[];
const renderer=createRenderer(canvas),input=createInput(),sound=createAudio({muted:!settings.sound,volume:settings.volume});
let world=createWorld({settings}),active=false,assetsReady=false,loadingAssets=false,shownEnd=false,loadedAssets=null;
let last=performance.now(),accumulator=0,resizeQueued=false,previousSize=null,screenMouse=null,returnFocus=null,lastAnnouncement='',dialogKind='',learningPanel=null;
let runId='',runSerial=0,lastEvent=0,lastSavedTime=0,lastQuota=false,tutorialShown=false;
const captured=new Map(),coarse=window.matchMedia('(any-pointer: coarse)');
const roleName=role=>role==='grasshopper'?'메뚜기':'개구리';
const stageName=stage=>getStage(stage,0).title??getStage(stage,0).name??['첫 한입','이번에는 메뚜기','어느 먹이를 노릴까','숨을 곳이 줄었다','먹이 길이 달라졌다','두 생물의 하루'][stage-1];
const unit=w=>w.role==='grasshopper'?'입':'마리';
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function button(text,callback,kind=''){const e=element('button',text,kind);e.type='button';e.addEventListener('click',callback);return e;}
function paragraph(text,className){return element('p',text,className);}
function announce(text){if(text!==lastAnnouncement){$('announcement').textContent=text;lastAnnouncement=text;}}
function persistSettings(){save.write('settings',settings);document.body.classList.toggle('large-controls',Boolean(settings.largeButtons));document.body.classList.toggle('reduced-motion',Boolean(settings.reducedMotion));sound.setMuted(!settings.sound);sound.setVolume(settings.volume);updateTouchLayout();}
function refreshHome(){const count=Object.keys(progress.completed??{}).filter(k=>progress.completed[k]).length;$('completion-summary').textContent=count===6?'여섯 단계 완주! 두 생물의 하루를 함께했어요':`${count} / 6 단계 완료 · 모든 단계와 교사 활동을 바로 열 수 있어요`;$('checkpoint-resume').hidden=!checkpoint;$('start').disabled=!assetsReady;}
function archive(){if(!active||!runId)return;runs=upsertRun(runs,runRecord(world,runId));save.write('runs',runs);lastSavedTime=world.time;}
function allRecords(){return active&&runId?upsertRun(runs,runRecord(world,runId)):runs;}
function drawStick(){const{x,y}=input.stick,travel=Math.max(12,($('pad').getBoundingClientRect().width-48)/2);$('stick').style.transform=`translate(${x*travel}px,${y*travel}px)`;}
function clearInput(){input.clear();screenMouse=null;if(world?.player)clearPendingInput(world);const list=[...captured];captured.clear();for(const[id,e]of list)try{if(e.hasPointerCapture(id))e.releasePointerCapture(id);}catch{}drawStick();}
const lifecycle=createLifecycle(({started,paused,dialogOpen,reason})=>{pauseWorld(world,paused);clearInput();input.setEnabled(active&&started&&!paused&&world.status==='playing');accumulator=0;last=performance.now();$('pause').textContent=paused?'계속':'일시정지';$('pause').setAttribute('aria-label',paused?'게임 계속하기':'게임 일시정지');$('pause-overlay').hidden=!active||!paused||dialogOpen||world.status!=='playing';$('pause-reason').textContent=reason||'일시정지';if(paused)sound.stop();});
function closeDialog({resume=true}={}){if(!dialog.open)return;learningPanel?.destroy();learningPanel=null;dialog.close();dialogKind='';lifecycle.closeDialog();if(!resume&&active)lifecycle.pause(true);const target=active&&!world.paused?canvas:returnFocus?.isConnected?returnFocus:$('start');target?.focus({preventScroll:true});}
function showDialog(title,kind='general',wide=false){learningPanel?.destroy();learningPanel=null;if(!dialog.open){returnFocus=document.activeElement;lifecycle.openDialog();}dialogKind=kind;$('dialog-title').textContent=title;$('dialog-content').replaceChildren();dialog.classList.toggle('wide',wide);$('dialog-close').hidden=kind==='intro';if(!dialog.open)dialog.showModal();return $('dialog-content');}
function resume(){if(!active||dialog.open||world.status!=='playing')return;lifecycle.pause(false);canvas.focus({preventScroll:true});sound.unlock();}
function interrupt(reason){if(!active)return;lifecycle.interrupt(reason);archive();}
function showHome(){archive();closeDialog({resume:false});active=false;clearInput();world.paused=true;$('game').hidden=true;$('entry').hidden=false;refreshHome();$('start').focus({preventScroll:true});}
function setWorld(next,{archivePrevious=true}={}){if(archivePrevious)archive();world=next;runId=`${Date.now().toString(36)}-${++runSerial}`;lastEvent=0;lastSavedTime=0;lastQuota=false;shownEnd=false;renderer.resetCamera();clearInput();previousSize=null;active=true;$('entry').hidden=true;$('game').hidden=false;closeDialog();lifecycle.start();queueResize();renderer.resize();renderer.render(world,0);canvas.focus({preventScroll:true});announce(`${world.stage}단계 ${stageName(world.stage)}. ${roleName(world.role)}로 먹이 ${world.quota}${unit(world)}를 먹고 ${world.destination.label}에 도착하세요.`);}
function beginStage(stage){if(!assetsReady)return;setWorld(createWorld({stage,settings}));sound.unlock();}
function intro(stage){const s=getStage(stage,0),role=s.role??(stage===2||stage===4?'grasshopper':'frog'),quota=s.quota??[4,6,6,6,6,3][stage-1],time=s.timeLimit??[90,120,120,120,150,75][stage-1];const box=showDialog(`${stage}단계 · ${stageName(stage)}`,'intro');box.append(element('span',roleName(role),'role-pill'),paragraph(stage===6?'두 생물의 하루를 이어 가요':role==='frog'?`곤충 ${quota}마리를 먹고 목적지까지!`:`풀 ${quota}입을 먹고 풀숲까지!`,'intro-target'));const facts=element('div',undefined,'intro-facts');for(const text of [stage===6?'개구리 75초 + 메뚜기 75초':`${time}초`,role==='frog'?'먹이: 곤충 · 천적: 뱀':'먹이: 풀 · 천적: 개구리','위기 탈출 1회'])facts.append(element('span',text));box.append(facts,paragraph(role==='frog'?'가까운 먹이에 표식이 뜨면 먹기를 누르세요. 목표를 채운 뒤 밝아진 도착 지점으로 이동하면 끝나요.':'풀 먹이 지점에서 먹기를 누르고 있으면 한 입씩 먹어요. 이동하면 이번 한 입만 멈추고, 이미 먹은 수는 남아요.'));if(stage===1)box.append(paragraph('먹으면 도약 준비가 빨라져요. 먹이 수·목적지·도약 준비 시간은 이 게임의 규칙이에요.','note'));if(stage===4)box.append(paragraph('2단계와 같은 조건에서 은신처 두 곳이 줄었어요. 남은 풀숲을 이어 이동해 보세요.','note'));if(stage===5)box.append(paragraph('3단계보다 메뚜기는 적고 애벌레는 그대로예요. 탐색할 시간은 30초 늘었어요.','note'));if(stage===6)box.append(paragraph('개구리로 먼저 도착한 뒤, 다른 개체인 메뚜기로 바뀌어요. 두 구간에는 각각 새 시간과 위기 탈출 기회가 있어요.'));const row=element('div',undefined,'button-row');row.append(button('출발!',()=>beginStage(stage),'primary'),button('단계 고르기',showStages));box.append(row);}
function showStages(){const box=showDialog('어느 하루를 만나 볼까요?','stages',true);box.append(paragraph('모든 단계는 처음부터 선택할 수 있어요. 여섯 단계를 어떤 도전 방식으로든 마치면 함께 완주를 축하해요.'));const grid=element('div',undefined,'stage-grid');for(let i=1;i<=6;i++){const s=getStage(i,0),card=button('',()=>intro(i),'stage-card');card.append(element('strong',`${i}. ${stageName(i)}`),element('small',i===6?'개구리 → 메뚜기 · 각각 75초':`${roleName(s.role??(i===2||i===4?'grasshopper':'frog'))} · ${s.timeLimit??[90,120,120,120,150,75][i-1]}초`));const completed=Boolean(progress.completed[i]),best=progress.bestScores?.[i],stars=progress.stars?.[i]??0;card.append(element('span',completed?'완료 ✓':'바로 도전할 수 있어요','completion'));if(best!==undefined)card.append(element('small',`기본 도전 최고 ${best}점 ${'★'.repeat(stars)}`));grid.append(card);}box.append(grid);const row=element('div',undefined,'button-row');row.append(button('교사용 생태 활동',showTeacher));if(active)row.append(button('현재 판으로',()=>closeDialog()));else row.append(button('시작 화면',()=>closeDialog()));box.append(row);}
function showTeacher(){archive();const box=showDialog('교사용 생태 활동','teacher',true);box.append(paragraph('게임 진행과 별개인 선택 활동입니다. 이 화면을 닫으면 같은 판을 이어갈 수 있어요. 모든 기록은 이 기기에만 저장됩니다.','note'));const host=element('div',undefined,'learning-panel');box.append(host);learningPanel=renderLearningPanel(host,{records:allRecords(),activityState:activities,onSave:value=>{activities=value;return save.write('activities',activities);}});if(storageError)box.prepend(paragraph('이 브라우저에서 저장 공간을 사용할 수 없어 이번 창 안에서만 기록이 유지될 수 있어요.','storage-note'));}
function showRecords(){const box=showDialog('게임 모형 속 이번 플레이 기록','records');const important=world.events.filter(e=>['ate','escape-used','capture','predator-attack','predator-warning'].includes(e.type));box.append(paragraph('게임 안에서 기록한 사건입니다. 실제 자연 관찰 자료나 과학 성적이 아니에요. 공격 예고는 먹히는 장면과 다릅니다.','note'));const list=element('ol',undefined,'record-list');for(const e of important){const relation=e.type==='ate'?`${e.food==='grass'?'풀':e.food==='caterpillar'?'애벌레':'메뚜기'} → ${e.eater==='grasshopper'?'메뚜기':'개구리'}`:e.type==='escape-used'?'위기 탈출 기회 사용':e.type==='predator-warning'?'천적 공격 예고':e.type==='predator-attack'?'천적 공격':'포획';list.append(element('li',`${Number(e.time).toFixed(1)}초 · ${relation}${e.observed===false?' · 화면 밖 모형 사건':''}`));}box.append(important.length?list:paragraph('아직 기록된 먹기나 공격 장면이 없어요.'));box.append(button('교사용 생태 활동에서 전체 기록 보기',showTeacher));}
function checkbox(box,label,key,{difficulty=false}={}){const row=element('label'),check=element('input');check.type='checkbox';check.checked=Boolean(settings[key]);row.append(check,document.createTextNode(label));check.addEventListener('change',()=>{settings[key]=check.checked;if(active)applySettings(world,settings);persistSettings();if(difficulty)announce('도움 설정이 적용됐어요. 단계 완료는 같게 인정하고 기본 최고점과는 따로 기록해요.');});box.append(row);}
function showSettings(){const box=showDialog('조작과 설정','settings');box.append(paragraph('방향키 / WASD 이동 · J / Z 먹기 · K / X / SPACE 큰 도약 · ESC 일시정지'),paragraph('메뚜기는 풀에서 먹기를 누르고 유지해요. 도약은 한 번씩 눌러요. 준비되지 않은 도약은 예약되지 않으며, 표시된 준비 시간이 끝난 뒤 다시 누르면 돼요.'));const access=element('fieldset',undefined,'settings-group');access.append(element('legend','편하게 조작하기 · 최고점 조건 유지'));checkbox(access,'화면 조작 버튼 항상 표시','showTouch');checkbox(access,'행동 버튼 크게','largeButtons');checkbox(access,'먹기 버튼 유지 허용','eatHold');checkbox(access,'장식 동작 줄이기','reducedMotion');checkbox(access,'마우스 방향으로 이동','mouse');box.append(access);const difficulty=element('fieldset',undefined,'settings-group');difficulty.append(element('legend','난도 도움 · 완료와 축하는 똑같이'));checkbox(difficulty,'공격 예고를 1.8초로 늘리기','longWarning',{difficulty:true});checkbox(difficulty,'천적 이동·공격을 80% 속도로','slowPredators',{difficulty:true});checkbox(difficulty,'시간 제한 없이','untimed',{difficulty:true});box.append(difficulty,paragraph('도움을 사용하거나 실패 뒤 이어 체험하면 단계 완료는 인정하고, 기본 도전 최고점·점수 별에는 섞지 않아요.','note'));const audio=element('fieldset',undefined,'settings-group');audio.append(element('legend','소리'));checkbox(audio,'효과음 켜기','sound');const volume=element('label','음량 '),range=element('input');range.type='range';range.min='0';range.max='1';range.step='.05';range.value=String(settings.volume);range.setAttribute('aria-label','효과음 음량');range.addEventListener('input',()=>{settings.volume=Number(range.value);persistSettings();});volume.append(range);audio.append(volume,button('소리 확인',()=>{sound.unlock();sound.play('eat');}));box.append(audio);const details=element('details');details.append(element('summary','기기 안 기록과 새로 시작'));details.append(paragraph('이름이나 로그인 없이 단계 완료·최고점·도움 설정·활동 답변을 이 기기에 저장해요. 다른 학생이 사용할 때는 아래에서 확인 후 기록을 비울 수 있어요.'));details.append(button('새 학생용으로 기록 비우기',()=>showResetConfirmation()));box.append(details);}
function showResetConfirmation(){const box=showDialog('이 기기의 기록을 비울까요?','reset');box.append(paragraph('단계 완료·최고점·교사 활동 답변·플레이 기록이 모두 지워집니다. 내려받거나 다른 곳에 보관하지 않았다면 되돌릴 수 없어요.'));const row=element('div',undefined,'button-row');row.append(button('취소',showSettings),button('기록 비우기',()=>{if(!save.clear()){const error=showDialog('기록을 모두 지우지 못했어요','reset-error');error.append(paragraph('브라우저 저장소에서 일부 기록이 남아 있을 수 있어요. 삭제 완료로 처리하지 않았습니다. 이 사이트의 저장 데이터 설정을 확인한 뒤 다시 시도해 주세요.'),button('설정으로 돌아가기',showSettings));return;}progress=createProgress();activities={};runs=[];checkpoint=null;settings={...normalizeSettings({}),sound:true,volume:.45,showTouch:false,mouse:false};active=false;persistSettings();showHome();},'primary'));box.append(row);}
function renderResult(){archive();const score=calculateScore(world);if(world.status==='success'){progress=recordCompletion(progress,world);save.write('progress',progress);if(world.stage===6){checkpoint=null;save.write('checkpoint',null);}}const win=world.status==='success',complete=win&&campaignComplete(progress);const title=complete?'여섯 단계 완주!':win?`${world.stage}단계 완료!`:'한 번 더 해볼까요?';const box=showDialog(title,'result');const hero=element('div',undefined,'result-hero');hero.append(element('strong',win?'함께 해냈어요!':'다음 길이 있어요'),paragraph(win?(world.stage===6?'개구리와 메뚜기가 각자의 목적지에 도착했어요.':'먹이 목표를 채우고 목적지에 도착했어요.'):world.reason));if(complete)hero.append(paragraph('먹고 피하며 살아가는 두 생물의 하루를 모두 만났어요.','celebration'));box.append(hero);if(world.route?.length){const map=element('canvas');map.className='route-recap';map.setAttribute('role','img');map.setAttribute('aria-label',world.stage===6&&world.segment===1?'게임 속 개구리와 메뚜기의 실제 이동 기록':'이번 게임 속 실제 이동 기록');drawRouteRecap(map,world,loadedAssets?.ground);box.append(paragraph('게임 속 이동 기록 · 밝은 점은 실제로 먹은 위치','small-note'),map);if(world.stage===6&&world.segment===1)box.append(paragraph('민트색: 개구리 · 노란색: 메뚜기','small-note'));}const foodEvents=world.events.filter(e=>e.type==='ate');if(foodEvents.length){const kinds=[...new Set(foodEvents.map(e=>e.food))].map(f=>f==='grass'?'풀':f==='caterpillar'?'애벌레':'메뚜기');box.append(paragraph(`이번 구간에서는 ${kinds.join('·')}${world.role==='grasshopper'?'를 먹었어요.':'를 먹었어요.'} 먹은 수 ${world.player.eaten}${unit(world)} · 위기 탈출 ${world.escapeRemaining?'남음':'사용'}`));}if(win&&score.eligible){box.append(paragraph(`${'★'.repeat(score.stars)} ${score.total}점`,'result-score'));const detail=element('div',undefined,'score-detail');for(const[label,value]of [['목표 달성 + 도착',score.base],['위기 탈출 미사용',score.escape],['선택 먹이 (최대 두 개)',score.extra],['도착 시간',score.time]]){detail.append(element('span',label),element('span',`${value??0}점`));}if(world.stage===6)detail.append(element('span','두 구간 점수 평균 (소수점 버림)'),element('strong',`${score.total}점`));box.append(detail);}else if(win)box.append(paragraph('완료 기록 ✓ · 도움·이어 체험·후반 재도전도 같은 단계 완료예요. 이 판은 기본 최고점·점수 별을 갱신하지 않아요.','note'));else box.append(paragraph('재도전 횟수 제한이나 대기 벌칙은 없어요. 도움 설정은 그대로 유지돼요.','note'));box.append(paragraph('점수와 별은 조작 도전의 기록이며 과학 이해도·생태계 건강도가 아니에요.','small-note'));const row=element('div',undefined,'button-row');if(win&&world.stage<6)row.append(button('다음 단계',()=>intro(world.stage+1),'primary'));else if(win)row.append(button('다른 길로 다시 도전',()=>setWorld(retryWorld(world,{full:true})),'primary'));else row.append(button(world.stage===6&&world.segment===1?'메뚜기 구간 다시':'다시 도전',()=>setWorld(retryWorld(world)),'primary'));if(!win)row.append(button('이어 체험',()=>{archive();setWorld(continueWorld(world),{archivePrevious:false});}));if(world.stage===6&&world.segment===1)row.append(button('전체 다시 도전',()=>setWorld(retryWorld(world,{full:true}))));row.append(button('단계 선택',showStages),button('교사용 생태 활동',showTeacher));box.append(row);sound.play(win?'success':'failed');}
function renderTransition(){archive();checkpoint=world.checkpoint;save.write('checkpoint',checkpoint);const box=showDialog('개구리 도착! 이번에는 메뚜기','transition');box.append(paragraph('전반을 마쳤어요. 다른 개체인 메뚜기로 풀 4입을 먹고 풀숲에 도착해 보세요.','intro-target'),paragraph('새로운 75초 · 위기 탈출 다시 1회. 전반 기록은 보존해요.'));box.append(button('메뚜기로 출발',()=>{setWorld(advanceSegment(world));},'primary'));}

async function prepareAssets(){if(loadingAssets)return;loadingAssets=true;$('start').disabled=true;$('retry-assets').hidden=true;try{loadedAssets=await loadAssets();renderer.setAssets(loadedAssets);assetsReady=true;$('asset-status').textContent='준비됐어요 · 시작하기를 눌러 주세요';}catch(error){$('asset-status').textContent=`그림을 불러오지 못했어요. ${error.message}`;$('retry-assets').hidden=false;}finally{loadingAssets=false;refreshHome();}}
$('retry-assets').addEventListener('click',prepareAssets);$('start').addEventListener('click',()=>{sound.unlock();intro(1);});$('entry-stages').addEventListener('click',showStages);$('stages').addEventListener('click',showStages);for(const id of ['entry-teacher','teacher'])$(id).addEventListener('click',showTeacher);for(const id of ['entry-settings','help','compact-help'])$(id).addEventListener('click',showSettings);$('records').addEventListener('click',showRecords);$('pause-home').addEventListener('click',showHome);$('pause').addEventListener('click',()=>{if(world.status==='transition')renderTransition();else if(world.status!=='playing')renderResult();else world.paused?resume():lifecycle.pause(true);});$('resume').addEventListener('click',resume);$('dialog-close').addEventListener('click',()=>closeDialog());dialog.addEventListener('cancel',e=>{e.preventDefault();if(dialogKind==='intro')showStages();else closeDialog();});$('checkpoint-resume').addEventListener('click',()=>{if(checkpoint&&assetsReady)setWorld(createWorld({stage:6,segment:1,settings,checkpoint,segmentRetry:true}));});$('title-image').addEventListener('error',()=>$('entry-art').classList.add('artwork-failed'));
function updateTouchLayout(){document.body.classList.toggle('touch-ui',coarse.matches||navigator.maxTouchPoints>0||settings.showTouch);queueResize();}coarse.addEventListener?.('change',updateTouchLayout);
const interactive=e=>e?.closest?.('button,input,textarea,select,a,[contenteditable=true]');
window.addEventListener('keydown',event=>{if(!active||dialog.open)return;if(event.code==='Escape'&&!event.repeat){event.preventDefault();world.paused?resume():lifecycle.pause(true);return;}if(interactive(document.activeElement)||!GAME_KEYS.has(event.code)||world.paused||world.status!=='playing')return;event.preventDefault();input.keyDown(event.code,event.repeat);});window.addEventListener('keyup',event=>input.keyUp(event.code));document.addEventListener('focusin',event=>{if(interactive(event.target))clearInput();});window.addEventListener('blur',()=>interrupt('다른 창으로 이동했어요'));document.addEventListener('visibilitychange',()=>{if(document.hidden)interrupt('화면을 잠시 떠났어요');});window.addEventListener('pagehide',()=>interrupt('화면을 잠시 떠났어요'));window.addEventListener('pageshow',e=>{if(e.persisted){interrupt('이전 화면으로 돌아왔어요');queueResize();}});
function capture(element,id){try{element.setPointerCapture(id);captured.set(id,element);return true;}catch{input.endPointer(id,true);drawStick();return false;}}
function release(event){const e=captured.get(event.pointerId);captured.delete(event.pointerId);input.endPointer(event.pointerId,event.type!=='pointerup');drawStick();if(e)try{if(e.hasPointerCapture(event.pointerId))e.releasePointerCapture(event.pointerId);}catch{}}
function padPoint(e){const b=$('pad').getBoundingClientRect();return[e.pointerId,e.clientX-b.left-b.width/2,e.clientY-b.top-b.height/2,b.width*.34];}
$('pad').addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();if(input.startPad(...padPoint(e))){capture($('pad'),e.pointerId);drawStick();}});$('pad').addEventListener('pointermove',e=>{if(input.updatePad(...padPoint(e))){e.preventDefault();drawStick();}});
for(const [id,action]of [['eat','eat'],['jump','jump']]){const e=$(id);e.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;event.preventDefault();if(input.startAction(event.pointerId,action))capture(e,event.pointerId);});e.addEventListener('click',event=>{if(event.detail===0)input.queue(action);});}
for(const e of [$('pad'),$('eat'),$('jump')]){for(const type of ['pointerup','pointercancel','lostpointercapture'])e.addEventListener(type,release);e.addEventListener('contextmenu',event=>event.preventDefault());}
canvas.addEventListener('pointermove',e=>{if(!settings.mouse||e.pointerType==='touch')return;const b=canvas.getBoundingClientRect();screenMouse={x:e.clientX-b.left,y:e.clientY-b.top};});canvas.addEventListener('pointerleave',()=>{screenMouse=null;input.setMouse(null);});canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});if(e.pointerType!=='touch'&&e.button===0&&settings.mouse)input.queue('eat');});canvas.addEventListener('pointercancel',()=>{screenMouse=null;input.setMouse(null);});
function updateViewport(){const v=window.visualViewport;if(!v||Math.abs(v.scale-1)<.01){document.documentElement.style.setProperty('--app-height',`${v?.height||window.innerHeight}px`);document.documentElement.style.setProperty('--app-width',`${v?.width||window.innerWidth}px`);}}
function queueResize(){if(resizeQueued)return;resizeQueued=true;requestAnimationFrame(()=>{resizeQueued=false;updateViewport();if(!active)return;if(window.visualViewport&&Math.abs(window.visualViewport.scale-1)>=.01)interrupt('화면을 확대했어요');const box=canvas.getBoundingClientRect();if(box.width<1||box.height<1)return;if(previousSize&&(Math.abs(previousSize.width-box.width)>1||Math.abs(previousSize.height-box.height)>1))interrupt('화면 크기가 바뀌었어요');previousSize={width:box.width,height:box.height};renderer.resize();renderer.render(world,0);});}
if('ResizeObserver'in window)new ResizeObserver(queueResize).observe($('playfield'));window.addEventListener('resize',queueResize);window.visualViewport?.addEventListener?.('resize',queueResize);window.screen.orientation?.addEventListener?.('change',()=>{interrupt('화면 방향이 바뀌었어요');queueResize();});window.addEventListener('orientationchange',()=>{interrupt('화면 방향이 바뀌었어요');queueResize();});
function processEvents(){const events=world.events.slice(lastEvent);lastEvent=world.events.length;for(const e of events){if(e.type==='ate')sound.play('eat');else if(e.type==='jump')sound.play('jump');else if(e.type==='predator-warning'){sound.play('warning');if(world.stage===1&&!tutorialShown){tutorialShown=true;const box=showDialog('느낌표와 공격선을 봐요','tutorial');box.append(paragraph('뱀은 표시된 선을 향해 공격해요. 선 바깥으로 움직이거나, 준비된 큰 도약으로 넘으세요. 이륙과 착지 때는 조심!'),paragraph('닫으면 경고가 처음부터 다시 시작돼요.','small-note'),button('주변을 확인했어요',()=>closeDialog(),'primary'));}}else if(e.type==='escape-used'){sound.play('escape');announce('위기 탈출 기회를 썼어요. 남은 기회 0회.');}}const quota=world.player.eaten>=world.quota;if(quota&&!lastQuota){sound.play('goal');announce('먹기 목표 완료! 도착 지점으로 이동하세요.');}lastQuota=quota;}
function updateHud(){const p=world.player,ready=getJumpReadiness(world),quota=p.eaten>=world.quota,extras=Math.min(2,Math.max(0,p.eaten-world.quota));$('stage-label').textContent=`${world.stage} / 6 · ${stageName(world.stage)}${world.stage===6?(world.segment?' · 후반':' · 전반'):''}`;$('food').textContent=quota?`먹기 완료 · 선택 +${extras}/2`:`먹이 ${p.eaten} / ${world.quota}${unit(world)}`;$('timer').textContent=world.timed?`${Math.max(0,Math.ceil(world.timeLimit-world.time))}초`:'시간 제한 없음';$('escape').textContent=`위기 탈출 ${world.escapeRemaining}회`;$('escape').classList.toggle('used',world.escapeRemaining===0);$('mission').textContent=quota?`도착 지점으로! · ${world.destination.label}`:`${roleName(world.role)} · 먹이 ${world.quota}${unit(world)} 먹고 ${world.destination.label}으로`;$('mission').parentElement.classList.toggle('ready',quota);$('state').textContent=world.paused?'일시정지':world.predator?.state==='windup'?'! 공격 예고':stageName(world.stage);$('jump').setAttribute('aria-disabled',String(!ready.ready));$('jump-label').textContent=ready.label;$('eat-label').textContent=world.role==='grasshopper'?(p.grazeProgress>0?`${Math.floor(p.grazeProgress/.9*100)}% · 유지`:'꾹 누르기'):'J / Z';$('eat').setAttribute('aria-disabled',String(p.state==='jumping'||world.paused||world.status!=='playing'));if(world.status!=='playing')$('pause').textContent='결과';$('condition-label').textContent=world.continued?'이어 체험':world.scoreEligible?'기본 도전':'도움·체험 도전';$('status').textContent=p.feedback?.text??(quota?'목표 완료! 바로 도착하거나 선택 먹이 두 개에 도전해요':world.role==='grasshopper'?'풀 지점에서 먹기를 누르고 유지해요':'먹이 표식 확인 → 먹기 · 경고선은 도약으로 넘기');}
function frame(now){let dt=(now-last)/1000;last=now;if(dt>.25&&active&&!world.paused){interrupt('실행이 잠시 중단됐어요');dt=0;}dt=Math.min(Math.max(0,dt),SETTINGS.maxFrameDelta);if(active){renderer.render(world,dt);if(!world.paused)accumulator+=dt;else accumulator=0;if(screenMouse)input.setMouse(renderer.toWorld(screenMouse.x,screenMouse.y));while(accumulator>=SETTINGS.fixedStep){const command=input.consume(world.player);if(!settings.eatHold&&world.role!=='grasshopper')command.eatHeld=false;stepWorld(world,command);accumulator-=SETTINGS.fixedStep;}processEvents();updateHud();if(world.time-lastSavedTime>=8)archive();if(world.status!=='playing'&&!shownEnd){shownEnd=true;input.setEnabled(false);if(world.status==='transition')renderTransition();else renderResult();}}requestAnimationFrame(frame);}
persistSettings();updateViewport();refreshHome();prepareAssets();requestAnimationFrame(frame);
