/** Independent control replay. No player/food/predator mutations; all travel and actions use createInput. */
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import {createWorld,stepWorld,canStand,clearGroundPath,selectFoodTarget,distance,getJumpReadiness,advanceSegment,cameraTarget,smoothCamera,clamp,foodBudget,warningVisible,pointVisible} from '../src/core.js';
import {createInput} from '../src/input.js';
import {createProgress,recordCompletion,campaignComplete} from '../src/campaign.js';
import {ART} from '../src/motion.js';
import {viewportMetrics} from '../src/viewport.js';
import {computeVisibleBounds} from '../src/render.js';
const root=fileURLToPath(new URL('../',import.meta.url));
function pathFor(w,goal){const start=w.player,r=start.r;if(clearGroundPath(w,start,goal,r))return [goal];const step=40,nodes=[],map=new Map();for(let y=360;y<1300;y+=step)for(let x=280;x<1410;x+=step){const p={x,y};if(canStand(w,p,r)){p.i=nodes.length;nodes.push(p);map.set(`${x}:${y}`,p);}}const starts=nodes.filter(p=>distance(p,start)<90&&clearGroundPath(w,start,p,r)),ends=new Set(nodes.filter(p=>distance(p,goal)<90&&clearGroundPath(w,p,goal,r)).map(p=>p.i));if(!starts.length||!ends.size)return null;const open=starts.map(p=>({p,g:distance(p,start),f:distance(p,start)+distance(p,goal),prev:null})),seen=new Map(open.map(q=>[q.p.i,q]));let final=null;while(open.length){open.sort((a,b)=>a.f-b.f);const n=open.shift();if(n.closed)continue;n.closed=true;if(ends.has(n.p.i)){final=n;break;}for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){if(!dx&&!dy)continue;const p=map.get(`${n.p.x+dx*step}:${n.p.y+dy*step}`);if(!p||!clearGroundPath(w,n.p,p,r))continue;const g=n.g+distance(n.p,p),old=seen.get(p.i);if(!old||g<old.g){const q={p,g,f:g+distance(p,goal),prev:n};seen.set(p.i,q);open.push(q);}}}if(!final)return null;const path=[goal];for(let n=final;n;n=n.prev)path.unshift({x:n.p.x,y:n.p.y});while(path.length>1&&clearGroundPath(w,start,path[1],r))path.shift();return path;}
export function playStage(stage,{assistance=false,viewport=[960,540],world=null,onFrame=null,maxSeconds=240}={}){let w=world??createWorld({stage,settings:{assistance}}),input=createInput();input.setEnabled(true);input.startPad(1,0,0,34);const metrics=viewportMetrics(...viewport),camera=cameraTarget(w.player,{width:metrics.logicalWidth,height:metrics.logicalHeight/ART.groundY},w);let target=null,route=null,repath=0,lastEat=0,firstGoal=null,tick=0;const log=[],positions=[],failures=[];function move(d){const mag=Math.min(1,Math.max(.24,Math.hypot(d.x,d.y)/49)),n=Math.hypot(d.x,d.y)||1;input.updatePad(1,d.x/n*34*mag,d.y/n*ART.groundY*34*mag,34);}function stop(){input.updatePad(1,0,0,34);}function eat(value){if(value)input.keyDown('KeyJ');else input.keyUp('KeyJ');}for(tick=0;tick<maxSeconds*60&&w.status==='playing';tick++){const p=w.player;const ct=cameraTarget(p,{width:metrics.logicalWidth,height:metrics.logicalHeight/ART.groundY},w);smoothCamera(camera,ct,1/60);camera.x=w.width<=metrics.logicalWidth?w.width/2:clamp(camera.x,metrics.logicalWidth/2,w.width-metrics.logicalWidth/2);camera.y=w.height<=metrics.logicalHeight/ART.groundY?w.height/2:clamp(camera.y,metrics.logicalHeight/ART.groundY/2,w.height-metrics.logicalHeight/ART.groundY/2);w.visibleBounds=computeVisibleBounds(metrics,camera,[]);if(p.eaten>=w.quota&&!firstGoal)firstGoal=w.time;
if(p.state==='eating'||p.state==='jumping'){stop();eat(false);}else if(p.eaten>=w.quota){eat(false);target=w.destination;}else if(w.role==='grasshopper'){const patch=selectFoodTarget(w);if(patch){stop();eat(true);target=null;}else{eat(false);target=w.grass.filter(g=>g.remaining).sort((a,b)=>distance(p,a)-distance(p,b))[0];}}else{const selected=selectFoodTarget(w);if(selected&&Math.abs(selected.z??0)<3&&p.eatCooldown<=0){stop();eat(true);target=null;}else{eat(false);const candidates=[];for(const q of w.prey.filter(q=>q.alive&&!q.captured))for(const sign of [1,-1]){const stance={x:q.x-sign*120,y:q.y+90,face:sign,q:q.id};if(canStand(w,stance,p.r))candidates.push({stance,score:distance(p,stance)+(q.role==='grasshopper'?35:0)});}candidates.sort((a,b)=>a.score-b.score);if(!target?.q||!w.prey.find(q=>q.id===target.q&&q.alive)||tick>=repath){for(const c of candidates){const routeCandidate=pathFor(w,c.stance);if(routeCandidate){target=c.stance;route=routeCandidate;repath=tick+60;break;}}}}}
if(target&&!['eating','jumping'].includes(p.state)){if(!route||tick>=repath||target===w.destination&&lastEat!==p.eaten){route=pathFor(w,target);repath=tick+60;}if(route?.length){while(route.length>1&&distance(p,route[0])<14)route.shift();const next=route[0],d={x:next.x-p.x,y:next.y-p.y};if(distance(p,next)<8){if(target.face&&p.facing!==target.face){move({x:target.face*13,y:0});}else{stop();route=null;}}else move(d);}else stop();}
// Evade late warnings with a real jump only if a safe complete leap is available.
const s=w.predator;if(s.state==='windup'&&s.warningVisibleTime>(w.settings.longWarning?1.05:.55)&&getJumpReadiness(w).ready&&!['eating','jumping'].includes(p.state)){const dirs=[{x:0,y:-1},{x:0,y:1},{x:p.x<s.x?-1:1,y:0}];const d=dirs.find(d=>clearGroundPath(w,p,{x:p.x+d.x*166.4,y:p.y+d.y*166.4},p.r));if(d){move({x:d.x*100,y:d.y*100});input.keyDown('Space');} }else input.keyUp('Space');
const before=w.events.length,command=input.consume(p);stepWorld(w,command);if(w.events.length>before)for(const e of w.events.slice(before)){if(!['feeding-observed'].includes(e.type))log.push(e);if(e.type==='predator-attack'&&(!warningVisible(w,w.predator.warning)||!pointVisible(w,w.predator,w.predator.r)||e.warningDuration+1e-8<(w.settings.longWarning?1.8:1.2)))failures.push({tick,attack:e});}if(p.eaten!==lastEat){lastEat=p.eaten;route=null;target=null;repath=0;}if(tick%30===0)positions.push({tick,t:w.time,x:p.x,y:p.y,state:p.state,eaten:p.eaten});if(!foodBudget(w).valid)failures.push({tick,budget:foodBudget(w)});onFrame?.({w,tick,command,camera,metrics});}
return{world:w,report:{stage:w.stage,segment:w.segment,assistance,viewport,status:w.status,eaten:w.player.eaten,quota:w.quota,elapsed:w.time,afterQuota:firstGoal?w.time-firstGoal:null,escapeUsed:w.escapeUsed,ticks:tick,foodBudgetFailures:failures.filter(f=>f.budget).length,unsafeAttacks:failures.filter(f=>f.attack).length,events:log,positions,final:{x:w.player.x,y:w.player.y},reason:w.reason}};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const reports=[],completion=[];for(const assistance of [true,false]){let progress=createProgress();for(let stage=1;stage<=6;stage++){let result=playStage(stage,{assistance});reports.push(result.report);if(result.world.status==='transition'){result=playStage(stage,{assistance,world:advanceSegment(result.world)});reports.push(result.report);}progress=recordCompletion(progress,result.world);console.log(JSON.stringify({...result.report,events:undefined,positions:undefined}));}completion.push({assistance,complete:campaignComplete(progress),progress});}fs.writeFileSync(root+'qa/campaign-replay-report.json',JSON.stringify({method:'Actual createInput pad/key events and stepWorld; camera/occlusion math matches renderer. No teleports or AI removal. Controller is automated, not human usability proof.',reports,completion},null,2));if(completion.some(x=>!x.complete)||reports.some(x=>x.foodBudgetFailures||x.unsafeAttacks))process.exitCode=1;}
